-- ═══════════════════════════════════════════════════════════════════
-- 17 — PMOC Predial — schema inicial
-- Migração ADITIVA: só cria tabelas novas com prefixo `pred_`.
-- Nenhuma tabela existente é alterada. Nada de DROP.
--
-- Portado do app legado xPredial (SQLite) do DEV_ERP. Modelo de inspeção
-- predial por NBR 5674:2012 / NBR 16747:2020 / IBAPE-NA:2012:
--   local (árvore) → template de checklist → inspeção → itens com GUT → laudo
--
-- Diferenças em relação ao SQLite de origem:
--   · `gut_total` e `condicao` viram colunas geradas (no SQLite eram triggers)
--   · ids de local vêm do legado, então a identity é `by default` e o seed
--     acerta a sequência no final
-- Executar no SQL Editor do Supabase.
-- ═══════════════════════════════════════════════════════════════════

-- ── normas de referência ──
create table if not exists pred_normas (
  id integer generated by default as identity primary key,
  codigo text not null unique,
  titulo text not null,
  orgao text not null default 'ABNT',
  ano integer check (ano is null or ano between 1900 and 2100),
  descricao text,
  url text,
  ativo boolean not null default true
);

-- ── locais (árvore; parent_id aponta para o próprio pred_locais) ──
-- FK deferrable porque o seed insere em lotes e um filho pode aparecer
-- antes do commit do pai.
create table if not exists pred_locais (
  id integer generated by default as identity primary key,
  codigo text unique,
  neo text,
  nome text not null,
  tipo text,
  area text check (area is null or area in ('ADM', 'OPE', 'APA')),
  restricao text not null default 'civil'
    check (restricao in ('civil', 'militar', 'reservado', 'secreto', 'proibido')),
  parent_id integer references pred_locais(id) deferrable initially deferred,
  descricao text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

-- ── templates de checklist e seus itens ──
create table if not exists pred_checklist_templates (
  id integer generated by default as identity primary key,
  nome text not null,
  tipo_local text,
  descricao text,
  norma_ref text,
  ativo boolean not null default true
);

create table if not exists pred_checklist_itens (
  id integer generated by default as identity primary key,
  template_id integer not null references pred_checklist_templates(id) on delete cascade,
  sistema text not null,
  subsistema text,
  descricao text not null,
  ordem integer not null default 0,
  unique (template_id, sistema, descricao)
);

-- ── inspeções ──
create table if not exists pred_inspecoes (
  id integer generated by default as identity primary key,
  titulo text not null,
  local_id integer references pred_locais(id) on delete set null,
  template_id integer references pred_checklist_templates(id) on delete set null,
  responsavel_tecnico text,
  data_vistoria date,
  status text not null default 'planejada'
    check (status in ('planejada', 'em_execucao', 'aguardando_aprovacao',
                      'aprovada', 'reprovada', 'concluida')),
  nivel text not null default '1' check (nivel in ('1', '2', '3')),
  tipo_inspecao text not null default 'extrinseca'
    check (tipo_inspecao in ('intrinseca', 'extrinseca', 'ambas')),
  observacoes text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- ── itens da inspeção, com matriz GUT ──
-- Escala GUT do app legado: 0, 1, 3, 6 ,8 ou 10 por dimensão (máximo 1000).
-- Faixas: até 100 baixo · 101–400 atenção · acima de 400 crítico.
create table if not exists pred_inspecao_itens (
  id integer generated by default as identity primary key,
  inspecao_id integer not null references pred_inspecoes(id) on delete cascade,
  descricao text not null,
  categoria text,
  g smallint not null default 0 check (g in (0, 1, 3, 6, 8, 10)),
  u smallint not null default 0 check (u in (0, 1, 3, 6, 8, 10)),
  t smallint not null default 0 check (t in (0, 1, 3, 6, 8, 10)),
  gut_total integer generated always as (g * u * t) stored,
  condicao text generated always as (
    case
      when g * u * t > 400 then 'critico'
      when g * u * t > 100 then 'atencao'
      else 'ok'
    end
  ) stored,
  presente boolean not null default false,
  local_ref text,
  foto_ref text,
  item_origem text not null default 'manual'
    check (item_origem in ('template', 'manual')),
  observacao text,
  criado_em timestamptz not null default now()
);

-- ── laudos ──
create table if not exists pred_laudos (
  id integer generated by default as identity primary key,
  inspecao_id integer references pred_inspecoes(id) on delete set null,
  local_id integer references pred_locais(id) on delete set null,
  titulo text not null,
  tipo text not null default 'laudo_inspecao'
    check (tipo in ('laudo_inspecao', 'art', 'rrt', 'relatorio_fotog',
                    'plano_manutencao', 'outro')),
  numero_art text,
  responsavel text,
  data_emissao date,
  data_validade date,
  conteudo text,
  arquivo_path text,
  status text not null default 'rascunho'
    check (status in ('rascunho', 'emitido', 'arquivado')),
  criado_em timestamptz not null default now()
);

-- ── trilha de auditoria do fluxo da inspeção ──
create table if not exists pred_eventos (
  id integer generated by default as identity primary key,
  inspecao_id integer not null references pred_inspecoes(id) on delete cascade,
  de_status text,
  para_status text not null,
  responsavel text,
  motivo text,
  criado_em timestamptz not null default now()
);

-- ── índices (toda FK indexada + filtros de tela) ──
create index if not exists pred_locais_parent_idx on pred_locais (parent_id);
create index if not exists pred_locais_tipo_idx on pred_locais (tipo);
create index if not exists pred_checklist_itens_template_idx on pred_checklist_itens (template_id);
create index if not exists pred_checklist_itens_sistema_idx on pred_checklist_itens (sistema);
create index if not exists pred_inspecoes_local_idx on pred_inspecoes (local_id);
create index if not exists pred_inspecoes_template_idx on pred_inspecoes (template_id);
create index if not exists pred_inspecoes_status_idx on pred_inspecoes (status, data_vistoria desc);
create index if not exists pred_inspecao_itens_inspecao_idx on pred_inspecao_itens (inspecao_id);
create index if not exists pred_inspecao_itens_gut_idx on pred_inspecao_itens (gut_total desc);
create index if not exists pred_laudos_inspecao_idx on pred_laudos (inspecao_id);
create index if not exists pred_laudos_local_idx on pred_laudos (local_id);
create index if not exists pred_eventos_inspecao_idx on pred_eventos (inspecao_id);

-- ── grants + RLS ──
-- Leitura liberada para anon (cargo "observador" entra sem senha).
-- Escrita apenas para sessão autenticada.
do $$
declare
  tabela text;
begin
  foreach tabela in array array[
    'pred_normas', 'pred_locais', 'pred_checklist_templates', 'pred_checklist_itens',
    'pred_inspecoes', 'pred_inspecao_itens', 'pred_laudos', 'pred_eventos'
  ]
  loop
    execute format('grant select on %I to anon, authenticated', tabela);
    execute format('grant insert, update, delete on %I to authenticated', tabela);
    execute format('alter table %I enable row level security', tabela);

    execute format('drop policy if exists %I on %I', 'sel_anon_' || tabela, tabela);
    execute format('drop policy if exists %I on %I', 'sel_auth_' || tabela, tabela);
    execute format('drop policy if exists %I on %I', 'ins_' || tabela, tabela);
    execute format('drop policy if exists %I on %I', 'upd_' || tabela, tabela);
    execute format('drop policy if exists %I on %I', 'del_' || tabela, tabela);

    execute format('create policy %I on %I for select to anon using (true)', 'sel_anon_' || tabela, tabela);
    execute format('create policy %I on %I for select to authenticated using (true)', 'sel_auth_' || tabela, tabela);
    execute format('create policy %I on %I for insert to authenticated with check (true)', 'ins_' || tabela, tabela);
    execute format('create policy %I on %I for update to authenticated using (true) with check (true)', 'upd_' || tabela, tabela);
    execute format('create policy %I on %I for delete to authenticated using (true)', 'del_' || tabela, tabela);
  end loop;
end $$;

grant usage on schema public to anon, authenticated;
