-- ═══════════════════════════════════════════════════════════════════
-- 19 — Locais do CMASM viram registro compartilhado entre os módulos
--
-- Motivo: `pred_locais` foi importado da árvore do xPredial e mistura duas
-- coisas diferentes — 72 locais físicos (paióis, áreas externas) e 78 nós de
-- organograma (encarregados, chefes, direção). Cargo não é lugar. Além disso
-- os prédios reais do CMASM não estavam ali: eles vivem na Refrigeração
-- (`equipamentos.predio` / `.local`), de onde a migração 20 os importa.
--
-- O ERP de referência (DEV_ERP/cmms-erp) já separa assim: tabela `estrutura`
-- para o organograma e `locais` para o físico, ligadas por `estrutura_id`.
--
-- O que esta migração faz:
--   1. renomeia pred_locais → cmasm_locais (nada mais referenciava o nome)
--   2. cria cmasm_estrutura e move o organograma para lá, preservando os ids
--   3. arquiva (ativo = false) os nós de organograma em cmasm_locais
--   4. adiciona local_id, nullable, nas tabelas de ativos de todos os módulos
--
-- Nenhum dado é apagado. As colunas novas são nullable: quem não usa nem vê.
-- Executar no SQL Editor do Supabase.
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. renomeia a tabela e as políticas que carregam o nome antigo ──
do $$
declare
  politica text;
begin
  if exists (select 1 from pg_tables where schemaname = 'public' and tablename = 'pred_locais')
     and not exists (select 1 from pg_tables where schemaname = 'public' and tablename = 'cmasm_locais')
  then
    execute 'alter table pred_locais rename to cmasm_locais';

    for politica in
      select policyname from pg_policies where schemaname = 'public' and tablename = 'cmasm_locais'
    loop
      execute format('alter policy %I on cmasm_locais rename to %I',
                     politica, replace(politica, 'pred_locais', 'cmasm_locais'));
    end loop;
  end if;
end $$;

-- ── 2. organograma em tabela própria ──
create table if not exists cmasm_estrutura (
  id integer generated by default as identity primary key,
  codigo text unique,
  neo text,
  nome text not null,
  tipo text,
  parent_id integer references cmasm_estrutura(id) deferrable initially deferred,
  descricao text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create index if not exists cmasm_estrutura_parent_idx on cmasm_estrutura (parent_id);

-- ligação opcional: que seção ocupa determinado local
alter table cmasm_locais
  add column if not exists estrutura_id integer references cmasm_estrutura(id);
create index if not exists cmasm_locais_estrutura_idx on cmasm_locais (estrutura_id);

-- Move o organograma preservando os ids originais, para que a hierarquia
-- (parent_id) continue apontando para os mesmos nós.
insert into cmasm_estrutura (id, codigo, neo, nome, tipo, parent_id, descricao)
select id, codigo, neo, nome, tipo, parent_id, descricao
from cmasm_locais
where tipo in (
  'direcao', 'vice_direcao', 'chefe_gabinete', 'chefe_departamento', 'secretario_depto',
  'assessor', 'encarregado_divisao', 'encarregado_secao', 'encarregado_grupo', 'encarregado_servico'
)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('cmasm_estrutura', 'id'), coalesce(max(id), 1)) from cmasm_estrutura;

-- Nós de organograma que apontavam para um pai que ficou em cmasm_locais
-- (a raiz CMASM) perdem o parent: a raiz é local, não cargo.
update cmasm_estrutura
set parent_id = null
where parent_id is not null
  and parent_id not in (select id from cmasm_estrutura);

-- Arquiva em cmasm_locais o que agora vive em cmasm_estrutura.
update cmasm_locais
set ativo = false
where ativo
  and id in (select id from cmasm_estrutura);

-- ── 3. local_id nas tabelas de ativos de cada módulo ──
-- Aditivo e nullable: os módulos em produção seguem funcionando sem preencher.
alter table elet_ativos     add column if not exists local_id integer references cmasm_locais(id);
alter table fono_ativos     add column if not exists local_id integer references cmasm_locais(id);
alter table equipamentos    add column if not exists local_id integer references cmasm_locais(id);
alter table maq_ativos      add column if not exists local_id integer references cmasm_locais(id);
alter table transp_ativos   add column if not exists local_id integer references cmasm_locais(id);

create index if not exists elet_ativos_local_idx    on elet_ativos (local_id);
create index if not exists fono_ativos_local_idx    on fono_ativos (local_id);
create index if not exists equipamentos_local_idx   on equipamentos (local_id);
create index if not exists maq_ativos_local_idx     on maq_ativos (local_id);
create index if not exists transp_ativos_local_idx  on transp_ativos (local_id);

-- ── 4. grants + RLS da tabela nova ──
grant select on cmasm_estrutura to anon, authenticated;
grant insert, update, delete on cmasm_estrutura to authenticated;
alter table cmasm_estrutura enable row level security;

drop policy if exists sel_anon_cmasm_estrutura on cmasm_estrutura;
drop policy if exists sel_auth_cmasm_estrutura on cmasm_estrutura;
drop policy if exists ins_cmasm_estrutura on cmasm_estrutura;
drop policy if exists upd_cmasm_estrutura on cmasm_estrutura;
drop policy if exists del_cmasm_estrutura on cmasm_estrutura;

create policy sel_anon_cmasm_estrutura on cmasm_estrutura for select to anon using (true);
create policy sel_auth_cmasm_estrutura on cmasm_estrutura for select to authenticated using (true);
create policy ins_cmasm_estrutura on cmasm_estrutura for insert to authenticated with check (true);
create policy upd_cmasm_estrutura on cmasm_estrutura for update to authenticated using (true) with check (true);
create policy del_cmasm_estrutura on cmasm_estrutura for delete to authenticated using (true);

-- Conferência:
--   select count(*) from cmasm_estrutura;                      -- 78
--   select count(*) from cmasm_locais where ativo;             -- 72 (antes da migração 20)
--   select count(*) from cmasm_locais where not ativo;         -- 78
