-- ══════════════════════════════════════════════════════════════════
-- 52 — Acervo de documentos: normas, manuais, formulários e conceitos
--
-- A plataforma APLICA norma o tempo todo e não tem onde consultá-la.
-- `plano_tarefas.norma_ref` e `maq_planos.norma_ref` guardam o código
-- ("NBR 17037", "NR-10 / NBR 17037") como texto solto, e o código
-- sozinho não diz o título, não diz o órgão, não diz o ano da edição
-- vigente e não abre em lugar nenhum.
--
-- ── O ACHADO QUE DECIDE A FORMA DESTE ARQUIVO ─────────────────────
--
-- O registro de normas JÁ EXISTE: `pred_normas` (migração 17), com 10
-- linhas semeadas pela 18 — codigo, titulo, orgao, ano, descricao, url,
-- ativo. Nasceu dentro de /predial e por isso usa o prefixo do módulo,
-- mas o conteúdo nunca foi só predial: NR-19 é sobre explosivos, ou
-- seja, sobre os paióis de armamento, não sobre a edificação.
--
-- Criar aqui uma segunda tabela com uma coluna `norma` produziria DUAS
-- fontes de verdade para "que norma se aplica" — o erro que este
-- projeto já pagou e registrou em D-eq-08 (a demanda tinha de vir do
-- plano real, não de uma cópia) e em D-cal-01 (remarcar uma OS tinha de
-- gravar na mesma coluna que a lista lê). As duas divergiriam no
-- primeiro código atualizado só de um lado, sem erro nenhum.
--
-- Então: NORMA CONTINUA EM `pred_normas`, que ganha aqui duas colunas
-- aditivas, e o que é genuinamente novo — manual, formulário e conceito
-- — nasce em `cmasm_documentos`. Não é arranjo: uma norma técnica é
-- outro tipo de objeto, com código, órgão e ano, e é citada por
-- `norma_ref` nos planos; um manual ou um verbete de glossário não tem
-- nenhuma dessas três coisas. O `check` de `categoria` NÃO aceita
-- 'norma', de modo que o Postgres — e não a disciplina de quem escreve
-- — impede que uma norma seja gravada no lugar errado.
--
-- DÍVIDA DE NOME, REGISTRADA E NÃO PAGA: pelo critério da migração 49
-- (D-eq-01), uma tabela que vários módulos leem devia se chamar
-- `cmasm_normas`, não `pred_normas`. Renomear é aditivo no sentido de
-- não apagar dado, mas quebra `predial/app.js` publicado no instante em
-- que roda — e a ordem segura (frontend primeiro, migração depois,
-- D-cf8-25) não existe para um rename: não há estado intermediário em
-- que os dois nomes valham. O nome errado custa menos que a janela de
-- módulo quebrado. Fica anotado para o dia em que /predial for
-- republicado junto.
--
-- PREFIXO `cmasm_` na tabela nova, pelo mesmo critério de D-eq-01: o
-- acervo não pertence a um módulo. A página nasce dentro de
-- /refrigeracao por decisão do usuário, mas o conteúdo atravessa a
-- plataforma inteira, e um dia /eletrica vai querer o mesmo verbete.
--
-- Aditiva. Nada de `drop`. Aplicar no SQL editor do Supabase.
-- ══════════════════════════════════════════════════════════════════

-- ── 1. pred_normas ganha módulo e conferência de link ──────────────
--
-- `modulo` responde "a que parte da plataforma esta norma se aplica",
-- que é como a tela agrupa. Nulo = geral, vale para todas.
--
-- `url_conferido` é a data em que alguém ABRIU o link e ele respondeu.
-- Existe porque um link de norma apodrece em silêncio: o órgão
-- reorganiza o portal e a página passa a dizer "não encontrado" sem
-- que nada no sistema perceba. Com a data, a tela distingue link
-- conferido de link herdado, e quem consulta sabe o que está clicando.
-- Nulo não é erro — é "ninguém conferiu ainda", que é a verdade sobre
-- a maior parte do acervo no dia em que ele nasce.
alter table pred_normas add column if not exists modulo text;
alter table pred_normas add column if not exists url_conferido date;

comment on column pred_normas.modulo is
  'Modulo da plataforma a que a norma se aplica; nulo = geral.';
comment on column pred_normas.url_conferido is
  'Data em que o link foi aberto e respondeu. Nulo = nunca conferido.';

-- ── 2. cmasm_documentos: manual, formulário e conceito ─────────────
--
-- Três categorias, lista fechada NO BANCO (e não só na tela) porque o
-- valor indexa o agrupamento da página: uma categoria fora da lista não
-- daria erro, cairia num grupo que não existe e o documento sumiria da
-- tela sem nenhum aviso — o mesmo raciocínio de `tipo_uso` na migração
-- 47. E a lista não tem 'norma' de propósito: ver o cabeçalho.
create table if not exists cmasm_documentos (
  id integer generated by default as identity primary key,
  categoria text not null check (categoria in ('manual','formulario','conceito')),
  titulo text not null check (length(btrim(titulo)) > 0),
  -- Para 'conceito', o corpo do verbete. Para 'manual'/'formulario', o
  -- que o documento é e quando se usa.
  resumo text,
  -- De onde vem / quem emite. Fabricante do manual, órgão do
  -- formulário, ou a própria plataforma quando a tela é que emite.
  fonte text,
  modulo text,
  url text,
  url_conferido date,
  -- Onde a coisa é encontrada quando NÃO é um link: "página OS →
  -- Imprimir OS". Um formulário que o próprio sistema emite não tem
  -- URL, e dizer onde ele está é a informação que a pessoa procura.
  onde text,
  ordem integer not null default 0,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

comment on table cmasm_documentos is
  'Acervo de manuais, formularios e conceitos. Norma tecnica NAO entra aqui: fica em pred_normas, fonte unica.';

create index if not exists cmasm_documentos_cat_idx
  on cmasm_documentos (categoria, ordem, titulo);

-- ── 3. RLS ─────────────────────────────────────────────────────────
--
-- Mesmo padrão do resto da plataforma e das tabelas `cmasm_` da 49:
-- leitura aberta (o cargo Livre é observador SEM senha, logo `anon` —
-- fechar o select tiraria dele justamente a página de consulta, que é
-- o que ele mais tem a ganhar), escrita para admin e gestor.
alter table cmasm_documentos enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'cmasm_documentos_sel') then
    create policy cmasm_documentos_sel on cmasm_documentos
      for select to public using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'cmasm_documentos_write') then
    create policy cmasm_documentos_write on cmasm_documentos
      for all to authenticated
      using (exists (select 1 from usuarios u where u.id = auth.uid() and u.role in ('admin','gestor')))
      with check (exists (select 1 from usuarios u where u.id = auth.uid() and u.role in ('admin','gestor')));
  end if;
end $$;

grant select on cmasm_documentos to anon, authenticated;
grant insert, update, delete on cmasm_documentos to authenticated;
