-- ══════════════════════════════════════════════════════════════════
-- 54 — Fluxo de plano: serviço padrão, material por serviço e plano
--      por tipo de equipamento (/refrigeracao)
--
-- ── O DEFEITO QUE ISTO CONSERTA ────────────────────────────────────
--
-- O checklist da OS vem de `CHECKLIST`, uma constante no JavaScript com
-- QUATRO chaves: SPLIT, PISO/TETO, SELF CONTAINED, JANELA. O parque tem
-- SEIS tipos — CENTRAL (6 máquinas, entre elas as centrais do F21) e
-- CHILLER (1) não estão lá. E `checklistDaOS` termina em
-- `tabela[tipoEquip] || tabela['SPLIT']`: uma central de 30 TR não fica
-- sem checklist, ela recebe **o checklist do split**, em silêncio —
-- "limpeza dos filtros da evaporadora" numa máquina que não tem
-- evaporadora de split. Errado é pior que vazio: vazio alguém percebe.
--
-- Ao mesmo tempo `plano_tarefas` — o plano REAL, 9 tarefas da NBR 17037,
-- no banco desde a migração 04 — **não é lido por nenhuma tela deste
-- módulo**. O plano de verdade está no banco e a tela usa uma constante.
--
-- ── DECISÕES ───────────────────────────────────────────────────────
--
-- 1) `aplica_a` É O ESCOPO POR TIPO, e não uma coluna nova. A coluna já
--    existe desde a 04 (`text not null default 'TODOS'`), já se chama
--    "aplica a" e hoje vale 'TODOS' nas 9 linhas. Criar `tipo_equip` ao
--    lado dela produziria duas colunas respondendo "a que equipamento
--    esta tarefa se aplica" — o erro que D-eq-08 e a migração 52 já
--    registram. Passa a aceitar 'TODOS' ou um valor de
--    `equipamentos.tipo`.
--
-- 2) SEM LISTA FECHADA no tipo, ao contrário de `tipo_uso` (migração
--    47). Lá o valor indexava uma tabela de constantes e um valor fora
--    da lista cairia num default produzindo número plausível e errado.
--    Aqui o valor é casado contra `equipamentos.tipo`, que é texto livre
--    administrado pelo usuário: um `check` recusaria o sétimo tipo que
--    ele cadastrar. A honestidade vem da TELA, que mostra quantos
--    equipamentos cada regra alcança — uma regra que alcança zero
--    aparece como zero, em vez de sumir.
--
-- 3) `aplica_modelo` é refinamento OPCIONAL. O usuário pediu "por
--    tipo/modelo", e /maquinas de fato chaveia por `tipo_modelo` —
--    porque lá cada modelo tem manual próprio. Aqui `equipamentos.modelo`
--    é nulo em 117 das 175 linhas, então uma regra por modelo alcança um
--    terço do parque no melhor caso. Existe porque foi pedida e porque é
--    barata (uma coluna nula); a contagem na tela é o que impede que
--    pareça mais do que é.
--
-- 4) MATERIAL PENDURA NO SERVIÇO, não na tarefa do plano. Foi o que o
--    usuário pediu ("inclusão de materiais para serviços") e é a forma
--    certa: "limpeza de filtro consome 1 filtro" é verdade uma vez, não
--    uma vez por periodicidade. /maquinas pendura em `maq_plano_materiais`
--    (no plano) porque lá não existe catálogo de serviço; aqui existe.
--
-- 5) `servicos` e `servico_materiais` nascem SEM PREFIXO, a convenção
--    deste módulo (`equipamentos`, `materiais`, `os_itens`,
--    `plano_tarefas`) — ao contrário de `cmasm_documentos`, que é acervo
--    de plataforma. Serviço de climatização é deste módulo.
--
-- ── ESTADO DE CAMPO QUE ISTO ENCONTRA ──────────────────────────────
--
-- `materiais` (migração 44) está com **ZERO linhas**: o catálogo existe
-- e ninguém cadastrou nada. Então `servico_materiais` nasce vazia por
-- falta de material a apontar, não por decisão de forma — e a tela diz
-- isso, com o caminho para a página Estoque, em vez de mostrar uma
-- seção vazia sem explicação.
--
-- Aditiva. Nada de `drop`. Aplicar no SQL editor do Supabase.
-- ══════════════════════════════════════════════════════════════════

-- ── 1. catálogo de serviço padrão ──────────────────────────────────
create table if not exists servicos (
  id integer generated by default as identity primary key,
  codigo text unique,
  nome text not null check (length(btrim(nome)) > 0),
  descricao text,
  -- Minutos, não horas: a unidade em que se cronometra uma limpeza de
  -- filtro. `> 0` e não `>= 0` porque serviço de duração zero não é
  -- serviço — seria um dado que zera a soma de tempo sem avisar.
  tempo_padrao_min numeric check (tempo_padrao_min is null or tempo_padrao_min > 0),
  norma_ref text,
  ordem integer not null default 0,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

comment on table servicos is
  'Catalogo de servico padrao de climatizacao. O que se faz; o plano diz em que equipamento e de quanto em quanto tempo.';

-- ── 2. o que cada serviço consome ──────────────────────────────────
--
-- Aponta para `materiais` (migração 44), o catálogo que o Estoque já
-- administra — nunca uma segunda lista de peças.
create table if not exists servico_materiais (
  id integer generated by default as identity primary key,
  servico_id integer not null references servicos(id) on delete cascade,
  material_id integer not null references materiais(id) on delete cascade,
  quantidade numeric not null default 1 check (quantidade > 0),
  criado_em timestamptz not null default now(),
  -- Um material entra uma vez por serviço: duas linhas do mesmo material
  -- fariam a quantidade prevista depender da ordem de cadastro.
  unique (servico_id, material_id)
);

comment on table servico_materiais is
  'Material que cada servico padrao consome, do catalogo de materiais (migracao 44).';

create index if not exists servico_materiais_servico_idx on servico_materiais (servico_id);

-- ── 3. plano_tarefas ganha escopo e serviço ────────────────────────
--
-- `aplica_a` não é tocada: ela JÁ é o escopo, e as 9 linhas existentes
-- seguem em 'TODOS'.
alter table plano_tarefas add column if not exists aplica_modelo text;
alter table plano_tarefas add column if not exists servico_id integer references servicos(id);

comment on column plano_tarefas.aplica_a is
  'TODOS, ou um valor de equipamentos.tipo (SPLIT, CENTRAL, CHILLER...). Texto livre de proposito: tipo e cadastro do usuario.';
comment on column plano_tarefas.aplica_modelo is
  'Refinamento opcional por modelo. Nulo = vale para todo o tipo.';
comment on column plano_tarefas.servico_id is
  'Servico padrao que esta tarefa executa. Nulo = a tarefa se descreve por descricao, como as 9 originais.';

create index if not exists plano_tarefas_aplica_idx on plano_tarefas (aplica_a, ordem);

-- ── 4. RLS ─────────────────────────────────────────────────────────
--
-- Mesmo padrão do módulo e da plataforma: leitura aberta (o cargo Livre
-- é observador sem senha, logo `anon`, e consultar o plano é justamente
-- o que ele tem a ganhar), escrita para admin e gestor — o mesmo par de
-- cargos que `podeEditarCadastro()` já usa na tela.
alter table servicos          enable row level security;
alter table servico_materiais enable row level security;

do $$
declare t text;
begin
  foreach t in array array['servicos','servico_materiais']
  loop
    if not exists (select 1 from pg_policies where policyname = t||'_sel') then
      execute format('create policy %I on %I for select to public using (true)', t||'_sel', t);
    end if;
    if not exists (select 1 from pg_policies where policyname = t||'_write') then
      execute format(
        'create policy %I on %I for all to authenticated using (exists (select 1 from usuarios u where u.id = auth.uid() and u.role in (''admin'',''gestor''))) with check (exists (select 1 from usuarios u where u.id = auth.uid() and u.role in (''admin'',''gestor'')))',
        t||'_write', t);
    end if;
    execute format('grant select on %I to anon, authenticated', t);
    execute format('grant insert, update, delete on %I to authenticated', t);
  end loop;
end $$;
