-- ══════════════════════════════════════════════════════════════════
-- 60 — Gestão e Qualidade: 5W2H priorizado por GUT, indicadores, POP
-- e espinha de Ishikawa (/gestao, Fase 13, Onda B)
--
-- Hoje um plano de ação da manutenção vive em planilha e um indicador
-- vive na cabeça de quem calcula. A Onda A (shared/grafico.js,
-- indicadores.js, gantt.js, abc.js, gut.js, kanban.js, calendario.js)
-- já entregou os núcleos puros que DESENHAM essas ferramentas; esta
-- migração dá a elas onde GRAVAR. Sem estas cinco tabelas o /gestao
-- seria mais um painel que lê e não registra (D-11).
--
-- PREFIXO `ges_` — a convenção de módulo já usada por `maq_`, `transp_`,
-- `elet_`, `fono_`, `pred_`, `rep_` e `cal_`. Diferente de `cmasm_`
-- (migração 49): estas cinco tabelas pertencem ao módulo /gestao, que
-- as grava; o fato de o Painel e o Calendário também LEREM outros
-- módulos (`maq_os`, `transp_*`, `logs_manutencao`, `pred_*`, `cal_*`)
-- não move o dono do dado — o mesmo raciocínio que já separa
-- `maq_areas` (D-03) de `cmasm_locais`.
--
-- ADITIVA, SEM DROP — o projeto arquiva com `ativo = false`, nunca
-- apaga uma linha. Nenhuma tabela de outro módulo é tocada: o /gestao
-- lê `maq_*`, `transp_*`, `logs_manutencao`, `pred_*` e `cal_*` pela
-- aplicação, nunca por chave estrangeira daqui para lá (D-13-03,
-- key_links) — o esquema de outro módulo não muda por causa deste.
--
-- ORDEM DE PUBLICAÇÃO (mesma regra de D-cf8-25/D-6wy/D-500): o
-- frontend do /gestao (plano 13-06) vai a produção ANTES deste SQL.
-- A sonda própria — `GES_OK`, implementada naquele plano — mantém a
-- tela publicada se comportando como se este arquivo não existisse
-- enquanto ele não rodar: sem aba de Ações, sem cartão de indicador
-- gravável, sem POP, sem espinha de Ishikawa. Na ordem inversa o
-- frontend chamaria uma tabela inexistente sem nenhum aviso.
--
-- A LIÇÃO DA MIGRAÇÃO 28, registrada aqui de novo: `create table if
-- not exists` é silêncio sobre uma tabela que já existe com outra
-- forma — aplicar sem erro não prova que a tabela ficou com a forma
-- certa. O rodapé deste arquivo traz as consultas de conferência
-- (colunas, checks, policies) para rodar DEPOIS de aplicar, não só
-- confiar no "Success" do SQL Editor.
--
-- ESCRITO E CONFERIDO, NÃO APLICADO — este plano só produz o arquivo
-- e o gate que prova a forma; a aplicação é passo humano do usuário,
-- caso a caso, depois do deploy do frontend.
-- ══════════════════════════════════════════════════════════════════

-- ── 1) ges_acoes — o 5W2H, uma linha por ação, priorizada por GUT ──
--
-- Os sete campos do 5W2H: `o_que` é o único obrigatório — uma ação sem
-- descrição não é uma ação, os outros seis podem faltar no rascunho.
--
-- `g`, `u`, `t` só aceitam a MESMA escala fechada de `shared/gut.js`
-- (`GUT_ESCALA`) ou nulo — nulo é "não avaliado", nunca zero, a mesma
-- régua de `refrig_permanente`/D-500-02: um `default` afirmaria uma
-- avaliação que não aconteceu. `gut_total` é coluna GERADA a partir do
-- produto das três — nunca um número que a tela grava por conta
-- própria, senão a prioridade mostrada e a prioridade gravada podem
-- divergir (T-13-17). A multiplicação em si já propaga o nulo: `g * u
-- * t` com qualquer uma das três nula devolve nulo, sem precisar de
-- `case` — o mesmo comportamento que `gutTotal()` implementa em
-- JavaScript para o mesmo fim.
--
-- `status` é o fluxo PDCA da ação: aberta (`planejada`), em curso
-- (`em_execucao`), sendo conferida (`verificacao`), fechada
-- (`concluida`) ou abortada (`cancelada`) — lista fechada no banco,
-- além da tela, para um estado inventado ser recusado pelo Postgres
-- (T-13-18).
--
-- `modulo` e `ativo_ref` são TEXTO LIVRE, sem chave estrangeira — o
-- /gestao lê os outros módulos, nunca amarra o esquema deles (D-13-03,
-- key_links). Uma ação pode nascer sem nenhum dos dois: nem toda ação
-- vem de um ativo (uma ação de treinamento, por exemplo).
create table if not exists ges_acoes (
  id integer generated by default as identity primary key,
  o_que text not null,
  por_que text,
  onde text,
  quando date,
  quem text,
  como text,
  quanto numeric,
  g integer check (g is null or g in (0, 1, 3, 6, 8, 10)),
  u integer check (u is null or u in (0, 1, 3, 6, 8, 10)),
  t integer check (t is null or t in (0, 1, 3, 6, 8, 10)),
  gut_total integer generated always as (g * u * t) stored,
  status text not null default 'planejada'
    check (status in ('planejada', 'em_execucao', 'verificacao', 'concluida', 'cancelada')),
  modulo text,
  ativo_ref text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  criado_por text,
  atualizado_em timestamptz not null default now()
);

-- ── 2) ges_indicadores — a definição de cada indicador ──────────────
--
-- `codigo` é único mas ANULÁVEL — mesma régua de `materiais.codigo`
-- (migração 44): um indicador pode nascer sem código curto ainda.
-- `rotulo` é obrigatório, como `materiais.nome` — um indicador sem
-- rótulo não aparece em lugar nenhum do cartão do painel.
--
-- `meta` NULA é legítima: é o indicador sem referência, que a tela
-- mostra em tom neutro em vez de fingir um alvo que ninguém definiu.
-- `sentido` diz se "maior é melhor" ou "menor é melhor" — sem ele o
-- semáforo do cartão não sabe para que lado apontar. `faixa_atencao`
-- é a fração da meta a partir da qual o estado vira atenção; nula até
-- alguém calibrar a oficina.
create table if not exists ges_indicadores (
  id integer generated by default as identity primary key,
  codigo text unique,
  rotulo text not null,
  unidade text,
  meta numeric,
  sentido text not null check (sentido in ('maior', 'menor')),
  faixa_atencao numeric,
  modulo text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

-- ── 3) ges_indicador_valores — a série histórica ────────────────────
--
-- Um valor por (indicador, período): dois valores para o mesmo mês
-- seriam duas verdades sobre o mesmo período, e é isso que a
-- unicidade abaixo impede. A unicidade em (indicador_id, periodo) já
-- serve de índice para "todos os valores deste indicador" — indicador_id
-- é a coluna líder — pelo mesmo raciocínio que a migração 44 já
-- registrou para `estoque_movimentos (os_id, tipo)`: a chave
-- estrangeira não precisa de um segundo índice só dela quando já lidera
-- um índice composto.
create table if not exists ges_indicador_valores (
  id integer generated by default as identity primary key,
  indicador_id integer not null references ges_indicadores(id) on delete cascade,
  periodo date not null,
  valor numeric not null,
  criado_em timestamptz not null default now(),
  constraint ges_indicador_valores_unico unique (indicador_id, periodo)
);

-- ── 4) ges_pop — procedimento operacional padrão ────────────────────
--
-- `titulo` é obrigatório; `texto` pode ficar vazio no rascunho. Os dois
-- vínculos (`ativo_ref`, `plano_ref`) são NULOS e INDEPENDENTES — um
-- POP sem vínculo nenhum é o caso mais comum no começo, e não é chave
-- estrangeira para tabela de outro módulo pelo mesmo motivo de
-- `ges_acoes.ativo_ref`.
create table if not exists ges_pop (
  id integer generated by default as identity primary key,
  titulo text not null,
  texto text,
  modulo text,
  ativo_ref text,
  plano_ref text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  criado_por text
);

-- ── 5) ges_causas — a espinha do Ishikawa ───────────────────────────
--
-- Pertence à ação e não sobrevive a ela: `on delete cascade` — apagar
-- (arquivar) uma ação não devia deixar causas órfãs apontando para uma
-- ação que não existe mais. `categoria` são os 6M, em caixa baixa como
-- o resto do vocabulário fechado da plataforma.
create table if not exists ges_causas (
  id integer generated by default as identity primary key,
  acao_id integer not null references ges_acoes(id) on delete cascade,
  categoria text not null
    check (categoria in ('metodo', 'maquina', 'mao_de_obra', 'material', 'medicao', 'meio_ambiente')),
  causa text not null,
  criado_em timestamptz not null default now()
);

-- ── 6) Índices ───────────────────────────────────────────────────────
--
-- Chave estrangeira sem índice é o Pitfall que a skill de boas
-- práticas mais cobra (query-missing-indexes): `ges_causas.acao_id`
-- não lidera nenhum outro índice, então ganha o seu. `indicador_id` de
-- `ges_indicador_valores` já lidera o índice da unicidade acima — ver
-- o comentário da tabela 3.
--
-- `ges_acoes` por `status` e por `modulo` são os dois recortes que a
-- tela do Painel e da aba Ações sempre pede (D-13-03/D-13-06). O mesmo
-- recorte por `modulo` se repete em `ges_pop` e `ges_indicadores`
-- porque as telas de Ferramentas/POP e do Painel filtram por módulo do
-- mesmo jeito.
create index if not exists ges_acoes_status_idx on ges_acoes (status);
create index if not exists ges_acoes_modulo_idx on ges_acoes (modulo);
create index if not exists ges_causas_acao_id_idx on ges_causas (acao_id);
create index if not exists ges_pop_modulo_idx on ges_pop (modulo);
create index if not exists ges_indicadores_modulo_idx on ges_indicadores (modulo);

-- ── 7) RLS — leitura para todo mundo, escrita para quem autenticou ──
--
-- O padrão já vigente na plataforma inteira (D-13-05): leitura aberta
-- (o cargo Livre de shared/auth.js é observador sem senha, e fechar a
-- leitura quebraria o modo observador também neste módulo) e escrita
-- para qualquer sessão que tenha feito login, SEM checar cargo dentro
-- da policy — o cargo filtra só na tela (T-13-20, aceito: mudar essa
-- régua para toda a plataforma está fora do escopo desta fase).
--
-- Cada `create policy` vem precedido do `drop policy if exists` de
-- mesmo nome — `create policy` não aceita "if not exists", e é isto
-- que torna o bloco reexecutável (mesmo formato da migração 44).
alter table ges_acoes enable row level security;
alter table ges_indicadores enable row level security;
alter table ges_indicador_valores enable row level security;
alter table ges_pop enable row level security;
alter table ges_causas enable row level security;

drop policy if exists ges_acoes_sel on ges_acoes;
create policy ges_acoes_sel on ges_acoes for select to public using (true);
drop policy if exists ges_acoes_ins on ges_acoes;
create policy ges_acoes_ins on ges_acoes for insert to authenticated with check (true);
drop policy if exists ges_acoes_upd on ges_acoes;
create policy ges_acoes_upd on ges_acoes for update to authenticated using (true);
drop policy if exists ges_acoes_del on ges_acoes;
create policy ges_acoes_del on ges_acoes for delete to authenticated using (true);

drop policy if exists ges_indicadores_sel on ges_indicadores;
create policy ges_indicadores_sel on ges_indicadores for select to public using (true);
drop policy if exists ges_indicadores_ins on ges_indicadores;
create policy ges_indicadores_ins on ges_indicadores for insert to authenticated with check (true);
drop policy if exists ges_indicadores_upd on ges_indicadores;
create policy ges_indicadores_upd on ges_indicadores for update to authenticated using (true);
drop policy if exists ges_indicadores_del on ges_indicadores;
create policy ges_indicadores_del on ges_indicadores for delete to authenticated using (true);

drop policy if exists ges_indicador_valores_sel on ges_indicador_valores;
create policy ges_indicador_valores_sel on ges_indicador_valores for select to public using (true);
drop policy if exists ges_indicador_valores_ins on ges_indicador_valores;
create policy ges_indicador_valores_ins on ges_indicador_valores for insert to authenticated with check (true);
drop policy if exists ges_indicador_valores_upd on ges_indicador_valores;
create policy ges_indicador_valores_upd on ges_indicador_valores for update to authenticated using (true);
drop policy if exists ges_indicador_valores_del on ges_indicador_valores;
create policy ges_indicador_valores_del on ges_indicador_valores for delete to authenticated using (true);

drop policy if exists ges_pop_sel on ges_pop;
create policy ges_pop_sel on ges_pop for select to public using (true);
drop policy if exists ges_pop_ins on ges_pop;
create policy ges_pop_ins on ges_pop for insert to authenticated with check (true);
drop policy if exists ges_pop_upd on ges_pop;
create policy ges_pop_upd on ges_pop for update to authenticated using (true);
drop policy if exists ges_pop_del on ges_pop;
create policy ges_pop_del on ges_pop for delete to authenticated using (true);

drop policy if exists ges_causas_sel on ges_causas;
create policy ges_causas_sel on ges_causas for select to public using (true);
drop policy if exists ges_causas_ins on ges_causas;
create policy ges_causas_ins on ges_causas for insert to authenticated with check (true);
drop policy if exists ges_causas_upd on ges_causas;
create policy ges_causas_upd on ges_causas for update to authenticated using (true);
drop policy if exists ges_causas_del on ges_causas;
create policy ges_causas_del on ges_causas for delete to authenticated using (true);

-- ── 8) Comentários ───────────────────────────────────────────────────
comment on table ges_acoes is
  'Plano de ação 5W2H priorizado por GUT (Fase 13, D-11). gut_total é gerada a partir de g, u, t — '
  'nunca gravada pelo cliente. modulo/ativo_ref nomeiam a origem em texto, sem chave estrangeira: '
  'o /gestao lê os outros módulos, nunca amarra o esquema deles.';
comment on column ges_acoes.gut_total is
  'Produto g * u * t, coluna gerada e armazenada. Nula quando qualquer dimensão for nula — '
  '"não avaliado" nunca é confundido com prioridade zero.';
comment on table ges_indicadores is
  'Definição de indicador (código, rótulo, unidade, meta, sentido). meta nula é o indicador sem '
  'referência ainda — a tela mostra tom neutro em vez de fingir um alvo.';
comment on table ges_indicador_valores is
  'Série histórica de um indicador. Único valor por (indicador_id, periodo): dois valores para o '
  'mesmo período seriam duas verdades sobre o mesmo mês.';
comment on table ges_pop is
  'Procedimento operacional padrão. ativo_ref e plano_ref são vínculos soltos e independentes — '
  'um POP sem nenhum dos dois é o caso mais comum no começo.';
comment on table ges_causas is
  'Espinha do Ishikawa de uma ação (6M). Pertence à ação e não sobrevive a ela (on delete cascade).';

-- ══════════════════════════════════════════════════════════════════
-- 9) Conferência pós-aplicação (rodar DEPOIS, no SQL Editor — nunca
-- confiar só no "Success", a lição da migração 28):
--
-- select table_name, count(*) from information_schema.columns
--   where table_name in ('ges_acoes','ges_indicadores','ges_indicador_valores','ges_pop','ges_causas')
--   group by table_name order by table_name;
-- -- esperado: ges_acoes 19, ges_indicadores 10, ges_indicador_valores 5,
-- -- ges_pop 9, ges_causas 5
--
-- select conrelid::regclass::text as tabela, conname, pg_get_constraintdef(oid)
--   from pg_constraint
--   where conrelid::regclass::text in
--     ('ges_acoes','ges_indicadores','ges_indicador_valores','ges_pop','ges_causas')
--   order by tabela, conname;
-- -- esperado: os checks de g/u/t/status/sentido/categoria, a FK de acao_id
-- -- e indicador_id, e a unicidade de (indicador_id, periodo)
--
-- select tablename, count(*) from pg_policies
--   where tablename in ('ges_acoes','ges_indicadores','ges_indicador_valores','ges_pop','ges_causas')
--   group by tablename order by tablename;
-- -- esperado: 4 em cada uma das cinco (select + insert + update + delete)
--
-- select 'ges_acoes' t, count(*) from ges_acoes
--   union all select 'ges_indicadores', count(*) from ges_indicadores
--   union all select 'ges_indicador_valores', count(*) from ges_indicador_valores
--   union all select 'ges_pop', count(*) from ges_pop
--   union all select 'ges_causas', count(*) from ges_causas;
-- -- esperado: 0 em todas, no dia da aplicação
-- ══════════════════════════════════════════════════════════════════
