-- ══════════════════════════════════════════════════════════════════
-- 64 — Seed do listão de materiais de /refrigeracao (catálogo + kits)
--
-- 318 materiais em 20 grupos (tubulação, conexões, fluidos, elétrica,
-- peças de reposição, compressores, EPI, instrumentos, ferramentas e
-- aparelhos) e 14 kits de serviço. Gerado a partir do mesmo catálogo
-- do artifact "Listão Refrigeração CMASM" (versão 2026-09-28).
--
-- REQUER a migração 63 aplicada antes.
--
-- IDEMPOTENTE: on conflict do nothing em todos os inserts — rodar de
-- novo não duplica nem sobrescreve o que o setor já editou (saldo,
-- mínimo, preço). Para atualizar um item depois, edite na tela.
--
-- estoque_atual fica 0 (default). Todos os itens com estoque_minimo > 0
-- vão aparecer como "abaixo do mínimo" até o primeiro inventário — isso
-- é verdade (ninguém contou ainda), não defeito.
--
-- preco = referência por UNIDADE DE USO (m, kg, un…), da pesquisa de
-- preços de 28/09/2026 (mediana, sem desconto de Pix). Itens sem pesquisa
-- ficam com preco null.
-- ══════════════════════════════════════════════════════════════════

insert into materiais (codigo, nome, tipo, classe, grupo, unidade, embalagem, unidade_compra, estoque_minimo, preco, preco_data) values
  ('TUB-001', 'Tubo de cobre flexível (panqueca) 1/4" (6,35 mm), parede 1/32", NBR 7541', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 15, 'rolo 15 m', 30, 19.12, '2026-09-28'),
  ('TUB-002', 'Tubo de cobre flexível (panqueca) 3/8" (9,52 mm), parede 1/32", NBR 7541', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 15, 'rolo 15 m', 30, 29.2, '2026-09-28'),
  ('TUB-003', 'Tubo de cobre flexível (panqueca) 1/2" (12,70 mm), parede 1/32", NBR 7541', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 15, 'rolo 15 m', 30, 38.68, '2026-09-28'),
  ('TUB-004', 'Tubo de cobre flexível (panqueca) 5/8" (15,88 mm), parede 1/32", NBR 7541', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 15, 'rolo 15 m', 30, 50.41, '2026-09-28'),
  ('TUB-005', 'Tubo de cobre flexível (panqueca) 3/4" (19,05 mm), parede 1/32", NBR 7541', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 15, 'rolo 15 m', 15, 62.83, '2026-09-28'),
  ('TUB-006', 'Tubo de cobre flexível (panqueca) 7/8" (22,22 mm), parede 1/32", NBR 7541', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 15, 'rolo 15 m', 15, 61.43, '2026-09-28'),
  ('TUB-007', 'Tubo de cobre rígido 5/8" (15,88 mm), barra 5 m, NBR 13206', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 5, 'barra 5 m', 10, null, null),
  ('TUB-008', 'Tubo de cobre rígido 3/4" (19,05 mm), barra 5 m, NBR 13206', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 5, 'barra 5 m', 10, null, null),
  ('TUB-009', 'Tubo de cobre rígido 7/8" (22,22 mm), barra 5 m, NBR 13206', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 5, 'barra 5 m', 10, null, null),
  ('TUB-010', 'Tubo de cobre rígido 1.1/8" (28,58 mm), barra 5 m, NBR 13206', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 5, 'barra 5 m', 0, null, null),
  ('TUB-011', 'Tubo capilar de cobre 0,031" (0,79 mm), rolo 15 m', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 15, 'rolo 15 m', 0, null, null),
  ('TUB-012', 'Tubo capilar de cobre 0,042" (1,07 mm), rolo 15 m', 'consumivel', 'consumivel', 'TUBULAÇÃO', 'm', 15, 'rolo 15 m', 0, null, null),
  ('CON-001', 'Luva reta de cobre para solda 1/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 1.2, '2026-09-28'),
  ('CON-002', 'Luva reta de cobre para solda 3/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 2, '2026-09-28'),
  ('CON-003', 'Luva reta de cobre para solda 1/2"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 2.5, '2026-09-28'),
  ('CON-004', 'Luva reta de cobre para solda 5/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 2.98, '2026-09-28'),
  ('CON-005', 'Luva reta de cobre para solda 3/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 4.2, '2026-09-28'),
  ('CON-006', 'Luva reta de cobre para solda 7/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 7.55, '2026-09-28'),
  ('CON-007', 'Curva 90° de cobre para solda 1/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 2.8, '2026-09-28'),
  ('CON-008', 'Curva 90° de cobre para solda 3/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 3.55, '2026-09-28'),
  ('CON-009', 'Curva 90° de cobre para solda 1/2"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 5.89, '2026-09-28'),
  ('CON-010', 'Curva 90° de cobre para solda 5/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 8.45, '2026-09-28'),
  ('CON-011', 'Curva 90° de cobre para solda 3/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 15.16, '2026-09-28'),
  ('CON-012', 'Curva 90° de cobre para solda 7/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 10, 18.19, '2026-09-28'),
  ('CON-013', 'Curva 45° de cobre para solda 1/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 0, 6.84, '2026-09-28'),
  ('CON-014', 'Curva 45° de cobre para solda 3/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 4, 3, '2026-09-28'),
  ('CON-015', 'Curva 45° de cobre para solda 1/2"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 4, 2.95, '2026-09-28'),
  ('CON-016', 'Curva 45° de cobre para solda 5/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 4, 7.2, '2026-09-28'),
  ('CON-017', 'Curva 45° de cobre para solda 3/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 4, 9.74, '2026-09-28'),
  ('CON-018', 'Curva 45° de cobre para solda 7/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 4, 13.83, '2026-09-28'),
  ('CON-019', 'Curva 180° de cobre para solda 1/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 0, null, null),
  ('CON-020', 'Curva 180° de cobre para solda 3/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, 5.68, '2026-09-28'),
  ('CON-021', 'Curva 180° de cobre para solda 1/2"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, 9.89, '2026-09-28'),
  ('CON-022', 'Curva 180° de cobre para solda 5/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, 12.46, '2026-09-28'),
  ('CON-023', 'Curva 180° de cobre para solda 3/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, 18.92, '2026-09-28'),
  ('CON-024', 'Curva 180° de cobre para solda 7/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, 32.84, '2026-09-28'),
  ('CON-025', 'Luva de redução de cobre para solda 1/2" x 3/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, 6.05, '2026-09-28'),
  ('CON-026', 'Luva de redução de cobre para solda 5/8" x 3/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-027', 'Luva de redução de cobre para solda 5/8" x 1/2"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-028', 'Luva de redução de cobre para solda 3/4" x 1/2"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-029', 'Luva de redução de cobre para solda 3/4" x 5/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-030', 'Luva de redução de cobre para solda 7/8" x 3/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-031', 'Luva de redução de cobre para solda 7/8" x 5/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-032', 'Tê de cobre para solda 1/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-033', 'Tê de cobre para solda 3/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-034', 'Tê de cobre para solda 1/2"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-035', 'Tê de cobre para solda 5/8"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('CON-036', 'Tê de cobre para solda 3/4"', 'consumivel', 'consumivel', 'CONEXÕES DE COBRE', 'un', 1, 'un', 2, null, null),
  ('FLA-001', 'Porca flange (flare) SAE latão 1/4"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 20, 4.58, '2026-09-28'),
  ('FLA-002', 'Porca flange (flare) SAE latão 3/8"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 20, 6.9, '2026-09-28'),
  ('FLA-003', 'Porca flange (flare) SAE latão 1/2"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 20, 8.71, '2026-09-28'),
  ('FLA-004', 'Porca flange (flare) SAE latão 5/8"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 20, 12.5, '2026-09-28'),
  ('FLA-005', 'Porca flange (flare) SAE latão 3/4"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 6, 14.52, '2026-09-28'),
  ('FLA-006', 'União flare SAE latão 1/4"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 4, null, null),
  ('FLA-007', 'União flare SAE latão 3/8"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 4, null, null),
  ('FLA-008', 'União flare SAE latão 1/2"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 4, null, null),
  ('FLA-009', 'União flare SAE latão 5/8"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 4, null, null),
  ('FLA-010', 'Niple de redução / adaptador flare-solda 1/4"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 2, null, null),
  ('FLA-011', 'Niple de redução / adaptador flare-solda 3/8"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 2, null, null),
  ('FLA-012', 'Niple de redução / adaptador flare-solda 1/2"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 2, null, null),
  ('FLA-013', 'Niple de redução / adaptador flare-solda 5/8"', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 2, null, null),
  ('FLA-014', 'Válvula de acesso Schrader 1/4" SAE para solda', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 10, null, null),
  ('FLA-015', 'Obus (miolo) de válvula Schrader, pacote 10', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'pct', 1, 'pct', 2, null, null),
  ('FLA-016', 'Tampa de válvula de serviço 1/4" SAE com vedação', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 10, null, null),
  ('FLA-017', 'Adaptador de serviço R-410A/R-32 5/16" SAE fêmea x 1/4" SAE macho', 'consumivel', 'consumivel', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 4, null, null),
  ('FLA-018', 'Válvula de serviço (condensadora) 1/4"', 'peca', 'peca', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 1, null, null),
  ('FLA-019', 'Válvula de serviço (condensadora) 3/8"', 'peca', 'peca', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 1, null, null),
  ('FLA-020', 'Válvula de serviço (condensadora) 1/2"', 'peca', 'peca', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 1, null, null),
  ('FLA-021', 'Válvula de serviço (condensadora) 5/8"', 'peca', 'peca', 'CONEXÕES FLARE E VÁLVULAS', 'un', 1, 'un', 1, null, null),
  ('ISO-001', 'Isolamento elastomérico (tubo esponjoso) p/ tubo 1/4", parede 9 mm, barra 2 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'm', 2, 'barra 2 m', 20, 5.94, '2026-09-28'),
  ('ISO-002', 'Isolamento elastomérico (tubo esponjoso) p/ tubo 3/8", parede 9 mm, barra 2 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'm', 2, 'barra 2 m', 20, 6.29, '2026-09-28'),
  ('ISO-003', 'Isolamento elastomérico (tubo esponjoso) p/ tubo 1/2", parede 9 mm, barra 2 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'm', 2, 'barra 2 m', 20, 7.15, '2026-09-28'),
  ('ISO-004', 'Isolamento elastomérico (tubo esponjoso) p/ tubo 5/8", parede 9 mm, barra 2 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'm', 2, 'barra 2 m', 20, 7.86, '2026-09-28'),
  ('ISO-005', 'Isolamento elastomérico (tubo esponjoso) p/ tubo 3/4", parede 9 mm, barra 2 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'm', 2, 'barra 2 m', 10, 8.06, '2026-09-28'),
  ('ISO-006', 'Isolamento elastomérico (tubo esponjoso) p/ tubo 7/8", parede 9 mm, barra 2 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'm', 2, 'barra 2 m', 10, 9.62, '2026-09-28'),
  ('ISO-007', 'Fita PVC branca de acabamento para tubulação, 10 cm x 10 m (sem adesivo)', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'rolo', 1, 'rolo', 30, 5.15, '2026-09-28'),
  ('ISO-008', 'Fita PVC branca adesiva 10 cm x 10 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'rolo', 1, 'rolo', 10, null, null),
  ('ISO-009', 'Fita de alumínio adesiva 48 mm x 45 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'rolo', 1, 'rolo', 4, null, null),
  ('ISO-010', 'Fita isolante antichama 19 mm x 20 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'rolo', 1, 'rolo', 10, null, null),
  ('ISO-011', 'Fita de autofusão 19 mm x 10 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'rolo', 1, 'rolo', 4, null, null),
  ('ISO-012', 'Espuma expansiva de poliuretano, lata 500 ml', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'lata', 1, 'lata', 4, 23.9, '2026-09-28'),
  ('ISO-013', 'Canaleta de acabamento para ar-condicionado 60 mm, barra 2 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'barra', 1, 'barra', 6, null, null),
  ('ISO-014', 'Canaleta de acabamento para ar-condicionado 80 mm, barra 2 m', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'barra', 1, 'barra', 4, null, null),
  ('ISO-015', 'Curva/acessório para canaleta de acabamento 60 mm', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'un', 1, 'un', 6, null, null),
  ('ISO-016', 'Massa de calafetar (vedação de furo de parede) 350 g', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'un', 1, 'un', 4, null, null),
  ('ISO-017', 'Silicone neutro incolor 280 g', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'tubo', 1, 'tubo', 4, null, null),
  ('ISO-018', 'Abraçadeira de nylon 200 x 4,8 mm, pacote 100', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'pct', 1, 'pct', 5, null, null),
  ('ISO-019', 'Abraçadeira de nylon 300 x 4,8 mm, pacote 100', 'consumivel', 'consumivel', 'ISOLAMENTO E ACABAMENTO', 'pct', 1, 'pct', 3, null, null),
  ('GAS-001', 'Fluido refrigerante R-410A, cilindro 11,34 kg', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'kg', 11.34, 'cilindro 11,34 kg', 22.68, 87.13, '2026-09-28'),
  ('GAS-002', 'Fluido refrigerante R-32, cilindro 3 kg', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'kg', 3, 'cilindro 3 kg', 9, 111.36, '2026-09-28'),
  ('GAS-003', 'Fluido refrigerante R-32, cilindro 9 kg', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'kg', 9, 'cilindro 9 kg', 0, null, null),
  ('GAS-004', 'Fluido refrigerante R-22, cilindro 13,6 kg (apenas manutenção de parque existente)', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'kg', 13.6, 'cilindro 13,6 kg', 13.6, null, null),
  ('GAS-005', 'Fluido refrigerante R-134a, cilindro 13,6 kg', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'kg', 13.6, 'cilindro 13,6 kg', 0, null, null),
  ('GAS-006', 'Fluido refrigerante R-404A, cilindro 10,9 kg', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'kg', 10.9, 'cilindro 10,9 kg', 0, null, null),
  ('GAS-007', 'Nitrogênio industrial (recarga de cilindro 10 m³)', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'm³', 10, 'recarga 10 m³', 10, null, null),
  ('GAS-008', 'Óleo POE para compressor (R-410A/R-32), 1 L', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'L', 1, 'L', 2, null, null),
  ('GAS-009', 'Óleo mineral para compressor (R-22), 1 L', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'L', 1, 'L', 1, null, null),
  ('GAS-010', 'Óleo PVE para compressor inverter, 1 L', 'consumivel', 'consumivel', 'FLUIDOS E ÓLEOS', 'L', 1, 'L', 1, null, null),
  ('QUI-001', 'Limpa-serpentina alcalino (condensadora), 5 L', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'L', 5, 'galão 5 L', 10, null, null),
  ('QUI-002', 'Limpador de evaporadora não ácido / neutro, 5 L', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'L', 5, 'galão 5 L', 10, null, null),
  ('QUI-003', 'Bactericida/fungicida para ar-condicionado, 1 L', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'L', 1, 'L', 4, null, null),
  ('QUI-004', 'Pastilha antibactericida para bandeja de dreno', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'un', 1, 'un', 50, null, null),
  ('QUI-005', 'Desincrustante para dreno/bandeja, 1 L', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'L', 1, 'L', 2, null, null),
  ('QUI-006', 'Fluido de limpeza de circuito (flushing) R-141b ou substituto, lata 1 kg', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'kg', 1, 'kg', 2, null, null),
  ('QUI-007', 'Detector de vazamento em spray (espuma), 400 ml', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'frasco', 1, 'frasco', 4, null, null),
  ('QUI-008', 'Desengraxante multiuso, 5 L', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'L', 5, 'galão 5 L', 5, null, null),
  ('QUI-009', 'Pano de limpeza / estopa, pacote 1 kg', 'consumivel', 'consumivel', 'QUÍMICOS E LIMPEZA', 'pct', 1, 'pct', 5, null, null),
  ('QUI-010', 'Saco coletor de limpeza para split (bolsa de lavagem) até 24k', 'peca', 'ferramenta', 'QUÍMICOS E LIMPEZA', 'un', 1, 'un', 2, null, null),
  ('SOL-001', 'Vareta foscoper 0% prata (cobre-cobre), kg', 'consumivel', 'consumivel', 'SOLDA', 'kg', 1, 'kg', 1, null, null),
  ('SOL-002', 'Vareta de solda 5% prata, kg', 'consumivel', 'consumivel', 'SOLDA', 'kg', 1, 'kg', 0.5, null, null),
  ('SOL-003', 'Vareta de solda 15% prata, kg', 'consumivel', 'consumivel', 'SOLDA', 'kg', 1, 'kg', 0.25, null, null),
  ('SOL-004', 'Fluxo para solda prata, pote 250 g', 'consumivel', 'consumivel', 'SOLDA', 'pote', 1, 'pote', 1, null, null),
  ('SOL-005', 'Cilindro de gás MAPP / propileno para maçarico portátil', 'consumivel', 'consumivel', 'SOLDA', 'un', 1, 'un', 4, null, null),
  ('SOL-006', 'Recarga de oxigênio (cilindro pequeno de conjunto oxi-GLP)', 'consumivel', 'consumivel', 'SOLDA', 'un', 1, 'un', 2, null, null),
  ('SOL-007', 'Lixa d''água grão 220 (limpeza de tubo)', 'consumivel', 'consumivel', 'SOLDA', 'folha', 1, 'folha', 10, null, null),
  ('DRE-001', 'Mangueira cristal flexível 5/8" (para dreno)', 'consumivel', 'consumivel', 'DRENAGEM', 'm', 50, 'rolo 50 m', 50, null, null),
  ('DRE-002', 'Mangueira cristal flexível 3/4" (para dreno)', 'consumivel', 'consumivel', 'DRENAGEM', 'm', 50, 'rolo 50 m', 25, null, null),
  ('DRE-003', 'Mangueira corrugada flexível para dreno 16 mm', 'consumivel', 'consumivel', 'DRENAGEM', 'm', 30, 'rolo 30 m', 30, null, null),
  ('DRE-004', 'Tubo PVC soldável 20 mm (dreno), barra 6 m', 'consumivel', 'consumivel', 'DRENAGEM', 'm', 6, 'barra 6 m', 12, null, null),
  ('DRE-005', 'Tubo PVC soldável 25 mm (dreno), barra 6 m', 'consumivel', 'consumivel', 'DRENAGEM', 'm', 6, 'barra 6 m', 12, null, null),
  ('DRE-006', 'Joelho 90° PVC soldável 20 mm', 'consumivel', 'consumivel', 'DRENAGEM', 'un', 1, 'un', 10, null, null),
  ('DRE-007', 'Joelho 90° PVC soldável 25 mm', 'consumivel', 'consumivel', 'DRENAGEM', 'un', 1, 'un', 10, null, null),
  ('DRE-008', 'Luva PVC soldável 25 mm', 'consumivel', 'consumivel', 'DRENAGEM', 'un', 1, 'un', 10, null, null),
  ('DRE-009', 'Tê PVC soldável 25 mm', 'consumivel', 'consumivel', 'DRENAGEM', 'un', 1, 'un', 10, null, null),
  ('DRE-010', 'Adesivo para PVC, 175 g', 'consumivel', 'consumivel', 'DRENAGEM', 'tubo', 1, 'tubo', 2, null, null),
  ('DRE-011', 'Bomba de dreno mini (até 12 L/h, recalque ≥ 10 m), 220 V', 'peca', 'peca', 'DRENAGEM', 'un', 1, 'un', 2, null, null),
  ('DRE-012', 'Sifão/adaptador de dreno para evaporadora', 'consumivel', 'consumivel', 'DRENAGEM', 'un', 1, 'un', 4, null, null),
  ('FIX-001', 'Suporte de parede para condensadora 400 mm (par)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'par', 1, 'par', 4, null, null),
  ('FIX-002', 'Suporte de parede para condensadora 450 mm (par)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'par', 1, 'par', 4, null, null),
  ('FIX-003', 'Suporte de parede para condensadora 500 mm (par)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'par', 1, 'par', 4, null, null),
  ('FIX-004', 'Suporte de parede para condensadora 550 mm (par)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'par', 1, 'par', 2, null, null),
  ('FIX-005', 'Suporte de parede para condensadora 600 mm (par)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'par', 1, 'par', 2, null, null),
  ('FIX-006', 'Suporte de parede para condensadora 800 mm (par)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'par', 1, 'par', 1, null, null),
  ('FIX-007', 'Suporte de piso / base para condensadora (par)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'par', 1, 'par', 2, null, null),
  ('FIX-008', 'Coxim/calço de borracha antivibração para condensadora (jogo 4)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'jogo', 1, 'jogo', 4, null, null),
  ('FIX-009', 'Chumbador parabolt 3/8" x 3" zincado', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'un', 1, 'un', 40, 1.53, '2026-09-28'),
  ('FIX-010', 'Chumbador parabolt 5/16" x 2.1/2" zincado', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'un', 1, 'un', 40, null, null),
  ('FIX-011', 'Barra roscada 3/8" zincada, 1 m', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'barra', 1, 'barra', 10, 14.34, '2026-09-28'),
  ('FIX-012', 'Porca sextavada 3/8" zincada', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'un', 1, 'un', 100, 0.24, '2026-09-28'),
  ('FIX-013', 'Arruela lisa 3/8" zincada', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'un', 1, 'un', 100, 0.2, '2026-09-28'),
  ('FIX-014', 'Bucha de nylon S8 com parafuso 4,8 x 50 (pacote 100)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'pct', 1, 'pct', 4, null, null),
  ('FIX-015', 'Bucha de nylon S10 com parafuso 5,5 x 65 (pacote 50)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'pct', 1, 'pct', 2, null, null),
  ('FIX-016', 'Parafuso autoatarraxante 4,2 x 13 (pacote 100)', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'pct', 1, 'pct', 2, null, null),
  ('FIX-017', 'Perfilado perfurado 38 x 38, barra 3 m', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'barra', 1, 'barra', 4, null, null),
  ('FIX-018', 'Abraçadeira tipo D / copo para tubo 3/4"', 'consumivel', 'consumivel', 'FIXAÇÃO E SUPORTES', 'un', 1, 'un', 20, null, null),
  ('ELE-001', 'Cabo PP 3 x 1,5 mm² 300/500 V (interligação/alimentação)', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 0, null, null),
  ('ELE-002', 'Cabo PP 3 x 2,5 mm² 300/500 V (interligação/alimentação)', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 50, null, null),
  ('ELE-003', 'Cabo PP 4 x 1,5 mm² 300/500 V (interligação/alimentação)', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 50, null, null),
  ('ELE-004', 'Cabo PP 4 x 2,5 mm² 300/500 V (interligação/alimentação)', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 50, null, null),
  ('ELE-005', 'Cabo PP 4 x 4,0 mm² 300/500 V (interligação/alimentação)', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 0, 21.52, '2026-09-28'),
  ('ELE-006', 'Cabo PP 4 x 6,0 mm² 300/500 V (interligação/alimentação)', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 0, 37.14, '2026-09-28'),
  ('ELE-007', 'Cabo flexível 2,5 mm² 450/750 V', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 100, null, null),
  ('ELE-008', 'Cabo flexível 4,0 mm² 450/750 V', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 0, null, null),
  ('ELE-009', 'Cabo flexível 6,0 mm² 450/750 V', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 100, 'rolo 100 m', 0, null, null),
  ('ELE-010', 'Disjuntor DIN monopolar 10 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 1, null, null),
  ('ELE-011', 'Disjuntor DIN monopolar 16 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, null, null),
  ('ELE-012', 'Disjuntor DIN monopolar 20 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, null, null),
  ('ELE-013', 'Disjuntor DIN monopolar 25 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, null, null),
  ('ELE-014', 'Disjuntor DIN bipolar 16 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, null, null),
  ('ELE-015', 'Disjuntor DIN bipolar 20 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, 27.02, '2026-09-28'),
  ('ELE-016', 'Disjuntor DIN bipolar 25 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, null, null),
  ('ELE-017', 'Disjuntor DIN bipolar 32 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, null, null),
  ('ELE-018', 'Disjuntor DIN bipolar 40 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 1, null, null),
  ('ELE-019', 'Disjuntor DIN tripolar 20 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, null, null),
  ('ELE-020', 'Disjuntor DIN tripolar 32 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 3, 56.18, '2026-09-28'),
  ('ELE-021', 'Disjuntor DIN tripolar 40 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 1, null, null),
  ('ELE-022', 'Disjuntor DIN tripolar 50 A curva C', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 1, null, null),
  ('ELE-023', 'DPS classe II 275 V 20 kA', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 4, null, null),
  ('ELE-024', 'Contator tripolar 9 A bobina 220 V', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 2, null, null),
  ('ELE-025', 'Contator tripolar 12 A bobina 220 V', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 2, null, null),
  ('ELE-026', 'Contator tripolar 18 A bobina 220 V', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 2, null, null),
  ('ELE-027', 'Contator tripolar 25 A bobina 220 V', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 2, null, null),
  ('ELE-028', 'Contator tripolar 32 A bobina 220 V', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 1, null, null),
  ('ELE-029', 'Relé térmico de sobrecarga (faixa conforme motor)', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 2, null, null),
  ('ELE-030', 'Relé falta de fase / sequência de fase 220/380 V', 'peca', 'peca', 'ELÉTRICA', 'un', 1, 'un', 2, null, null),
  ('ELE-031', 'Terminal tubular (ilhós) sortido, caixa 500', 'consumivel', 'consumivel', 'ELÉTRICA', 'cx', 1, 'cx', 2, null, null),
  ('ELE-032', 'Conector de emenda tipo alavanca 3 vias, pacote 50', 'consumivel', 'consumivel', 'ELÉTRICA', 'pct', 1, 'pct', 2, null, null),
  ('ELE-033', 'Tomada 2P+T 20 A de sobrepor', 'consumivel', 'consumivel', 'ELÉTRICA', 'un', 1, 'un', 6, null, null),
  ('ELE-034', 'Caixa de passagem PVC 100x100 com tampa', 'consumivel', 'consumivel', 'ELÉTRICA', 'un', 1, 'un', 6, null, null),
  ('ELE-035', 'Eletroduto flexível corrugado 3/4"', 'consumivel', 'consumivel', 'ELÉTRICA', 'm', 25, 'rolo 25 m', 25, null, null),
  ('CAP-001', 'Capacitor de trabalho 1,5 µF 450 VAC (ventilador)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 4, null, null),
  ('CAP-002', 'Capacitor de trabalho 2 µF 450 VAC (ventilador)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 4, null, null),
  ('CAP-003', 'Capacitor de trabalho 2,5 µF 450 VAC (ventilador)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 4, null, null),
  ('CAP-004', 'Capacitor de trabalho 3 µF 450 VAC (ventilador)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 4, null, null),
  ('CAP-005', 'Capacitor de trabalho 4 µF 450 VAC (ventilador)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('CAP-006', 'Capacitor de trabalho 5 µF 450 VAC (ventilador)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('CAP-007', 'Capacitor de trabalho 6 µF 450 VAC (ventilador)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('CAP-008', 'Capacitor de trabalho 8 µF 450 VAC (ventilador)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('CAP-009', 'Capacitor de trabalho 15 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 1, null, null),
  ('CAP-010', 'Capacitor de trabalho 20 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 1, null, null),
  ('CAP-011', 'Capacitor de trabalho 25 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 3, null, null),
  ('CAP-012', 'Capacitor de trabalho 30 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 3, null, null),
  ('CAP-013', 'Capacitor de trabalho 35 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 3, null, null),
  ('CAP-014', 'Capacitor de trabalho 40 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 3, null, null),
  ('CAP-015', 'Capacitor de trabalho 45 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 3, null, null),
  ('CAP-016', 'Capacitor de trabalho 50 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 1, null, null),
  ('CAP-017', 'Capacitor de trabalho 55 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 1, null, null),
  ('CAP-018', 'Capacitor de trabalho 60 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 1, null, null),
  ('CAP-019', 'Capacitor de trabalho 70 µF 440 VAC (compressor)', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 1, null, null),
  ('CAP-020', 'Capacitor duplo 35+5 µF 440 VAC', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('CAP-021', 'Capacitor duplo 40+5 µF 440 VAC', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('CAP-022', 'Capacitor duplo 45+5 µF 440 VAC', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('CAP-023', 'Capacitor duplo 50+5 µF 440 VAC', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('CAP-024', 'Capacitor duplo 60+5 µF 440 VAC', 'peca', 'peca', 'PEÇAS — CAPACITORES', 'un', 1, 'un', 2, null, null),
  ('PLA-001', 'Placa universal para split hi-wall (até 36k), com controle remoto e receptor', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 3, null, null),
  ('PLA-002', 'Placa universal para piso-teto/cassete', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 1, null, null),
  ('PLA-003', 'Controle remoto universal para ar-condicionado', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 6, null, null),
  ('PLA-004', 'Sensor de temperatura NTC 10 kΩ (ambiente/serpentina)', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 6, null, null),
  ('PLA-005', 'Sensor de temperatura NTC 5 kΩ', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 4, null, null),
  ('PLA-006', 'Sensor de temperatura NTC 15 kΩ / 20 kΩ', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 4, null, null),
  ('PLA-007', 'Termostato mecânico / controlador de temperatura digital', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 2, null, null),
  ('PLA-008', 'Pressostato de alta', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 1, null, null),
  ('PLA-009', 'Pressostato de baixa', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 1, null, null),
  ('PLA-010', 'Relé de partida / protetor térmico de compressor (conforme modelo)', 'peca', 'peca', 'PEÇAS — ELETRÔNICA E SENSORES', 'un', 1, 'un', 2, null, null),
  ('PLA-011', 'Fusível de vidro/cerâmico 3,15 A e 5 A (placa), pacote 10', 'consumivel', 'consumivel', 'PEÇAS — ELETRÔNICA E SENSORES', 'pct', 1, 'pct', 2, null, null),
  ('PLA-012', 'Varistor / fusível térmico de placa (sortido)', 'consumivel', 'consumivel', 'PEÇAS — ELETRÔNICA E SENSORES', 'pct', 1, 'pct', 1, null, null),
  ('MOT-001', 'Motor ventilador evaporadora split 9k–12k', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-002', 'Motor ventilador evaporadora split 18k–24k', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-003', 'Motor ventilador evaporadora piso-teto', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-004', 'Motor ventilador condensadora 1/10 cv, 220 V', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 0, null, null),
  ('MOT-005', 'Motor ventilador condensadora 1/6 cv, 220 V', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-006', 'Motor ventilador condensadora 1/4 cv, 220 V', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-007', 'Motor ventilador condensadora 1/3 cv, 220 V', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-008', 'Motor ventilador condensadora 1/2 cv, 220 V', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 0, null, null),
  ('MOT-009', 'Motor de passo (swing) da aleta, 12 V', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 3, null, null),
  ('MOT-010', 'Turbina (rotor tangencial) evaporadora split (conforme modelo)', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-011', 'Hélice de condensadora 400 mm', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-012', 'Hélice de condensadora 450 mm', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-013', 'Hélice de condensadora 500 mm', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 1, null, null),
  ('MOT-014', 'Rolamento/bucha de motor ventilador (sortido)', 'peca', 'peca', 'PEÇAS — MOTORES E VENTILAÇÃO', 'un', 1, 'un', 2, null, null),
  ('CIC-001', 'Filtro secador 1/4" (split até 24k)', 'peca', 'peca', 'PEÇAS — CICLO FRIGORÍFICO', 'un', 1, 'un', 6, null, null),
  ('CIC-002', 'Filtro secador 3/8"', 'peca', 'peca', 'PEÇAS — CICLO FRIGORÍFICO', 'un', 1, 'un', 4, null, null),
  ('CIC-003', 'Filtro secador bidirecional (bomba de calor)', 'peca', 'peca', 'PEÇAS — CICLO FRIGORÍFICO', 'un', 1, 'un', 2, null, null),
  ('CIC-004', 'Válvula reversora 4 vias (conforme capacidade)', 'peca', 'peca', 'PEÇAS — CICLO FRIGORÍFICO', 'un', 1, 'un', 1, null, null),
  ('CIC-005', 'Válvula de expansão termostática (conforme capacidade/fluido)', 'peca', 'peca', 'PEÇAS — CICLO FRIGORÍFICO', 'un', 1, 'un', 0, null, null),
  ('CIC-006', 'Bobina de válvula solenoide / reversora 220 V', 'peca', 'peca', 'PEÇAS — CICLO FRIGORÍFICO', 'un', 1, 'un', 1, null, null),
  ('CIC-007', 'Acumulador de sucção (conforme capacidade)', 'peca', 'peca', 'PEÇAS — CICLO FRIGORÍFICO', 'un', 1, 'un', 0, null, null),
  ('CMP-001', 'Compressor rotativo 9.000 BTU/h R-410A 220 V', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 0, null, null),
  ('CMP-002', 'Compressor rotativo 12.000 BTU/h R-410A 220 V', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 1, null, null),
  ('CMP-003', 'Compressor rotativo 18.000 BTU/h R-410A 220 V', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 1, null, null),
  ('CMP-004', 'Compressor rotativo 24.000 BTU/h R-410A 220 V', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 1, null, null),
  ('CMP-005', 'Compressor rotativo 30.000 BTU/h R-410A 220 V', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 0, null, null),
  ('CMP-006', 'Compressor scroll 36.000 BTU/h R-410A 220 V', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 0, null, null),
  ('CMP-007', 'Compressor scroll 48.000 BTU/h R-410A 220 V', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 0, null, null),
  ('CMP-008', 'Compressor scroll 60.000 BTU/h R-410A 220 V', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 0, null, null),
  ('CMP-009', 'Compressor scroll 15 TR 380 V trifásico (self/central)', 'peca', 'peca', 'COMPRESSORES', 'un', 1, 'un', 0, null, null),
  ('FIL-001', 'Manta filtrante G4 para evaporadora/self, rolo 20 m x 1 m', 'consumivel', 'consumivel', 'FILTROS', 'm²', 20, 'rolo 20 m²', 20, null, null),
  ('FIL-002', 'Manta filtrante F5 / M5', 'consumivel', 'consumivel', 'FILTROS', 'm²', 20, 'rolo 20 m²', 0, null, null),
  ('FIL-003', 'Filtro de ar para split (tela de reposição, conforme modelo)', 'peca', 'peca', 'FILTROS', 'un', 1, 'un', 6, null, null),
  ('FIL-004', 'Filtro plissado G4 para self/central (conforme dimensão)', 'peca', 'peca', 'FILTROS', 'un', 1, 'un', 0, null, null),
  ('EPI-001', 'Luva nitrílica descartável, caixa 100', 'consumivel', 'consumivel', 'EPI', 'cx', 1, 'cx', 2, null, null),
  ('EPI-002', 'Luva de vaqueta / raspa (par)', 'peca', 'ferramenta', 'EPI', 'par', 1, 'par', 6, null, null),
  ('EPI-003', 'Luva criogênica / para fluido refrigerante (par)', 'peca', 'ferramenta', 'EPI', 'par', 1, 'par', 2, null, null),
  ('EPI-004', 'Óculos de proteção incolor', 'peca', 'ferramenta', 'EPI', 'un', 1, 'un', 6, null, null),
  ('EPI-005', 'Respirador PFF2', 'consumivel', 'consumivel', 'EPI', 'un', 1, 'un', 20, null, null),
  ('EPI-006', 'Protetor auricular tipo plug', 'consumivel', 'consumivel', 'EPI', 'par', 1, 'par', 20, null, null),
  ('EPI-007', 'Cinto paraquedista com talabarte duplo', 'peca', 'ferramenta', 'EPI', 'un', 1, 'un', 2, null, null),
  ('EPI-008', 'Capacete com jugular', 'peca', 'ferramenta', 'EPI', 'un', 1, 'un', 0, null, null),
  ('EPI-009', 'Botina de segurança (conforme numeração)', 'peca', 'ferramenta', 'EPI', 'par', 1, 'par', 0, null, null),
  ('EPI-010', 'Avental de raspa para solda', 'peca', 'ferramenta', 'EPI', 'un', 1, 'un', 1, null, null),
  ('INS-001', 'Manifold digital 4 vias com sensores de temperatura (R-410A/R-32)', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-002', 'Manifold analógico 2 vias R-410A/R-32', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-003', 'Jogo de mangueiras de serviço 1,5 m R-410A (3 un)', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-004', 'Bomba de vácuo 2 estágios 7 CFM', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-005', 'Vacuômetro digital (mícrons)', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-006', 'Balança digital para carga de fluido (até 100 kg)', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-007', 'Detector eletrônico de vazamento (heated diode/infravermelho)', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-008', 'Recolhedora de fluido refrigerante', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-009', 'Cilindro de recolhimento 13,6 kg (duas válvulas)', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-010', 'Alicate amperímetro true RMS com capacímetro', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-011', 'Multímetro digital true RMS', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-012', 'Termômetro infravermelho', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-013', 'Termo-higrômetro digital', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-014', 'Anemômetro de hélice (vazão/velocidade de ar)', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-015', 'Megômetro (teste de isolação de compressor)', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('INS-016', 'Terrômetro / detector de tensão sem contato', 'peca', 'ferramenta', 'INSTRUMENTOS', 'un', 1, 'un', 0, null, null),
  ('FER-001', 'Flangeador excêntrico 1/4" a 3/4" (R-410A)', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-002', 'Cortador de tubo de cobre 1/8" a 1.1/8"', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-003', 'Minicortador de tubo', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-004', 'Curvador de tubo tipo alavanca 1/4" a 7/8"', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-005', 'Jogo de molas curvadoras', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-006', 'Expansor/alargador de tubo 1/4" a 7/8"', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-007', 'Escareador/rebarbador', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-008', 'Kit de solda portátil oxi-GLP / MAPP', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-009', 'Chave de torque para porca flare (jogo)', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-010', 'Jogo de chaves de boca/estrela', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-011', 'Chave catraca para válvula de serviço', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-012', 'Jogo de chaves Allen', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-013', 'Lavadora de alta pressão (limpeza de serpentina)', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-014', 'Pulverizador manual 2 L', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-015', 'Escova para serpentina / pente de aletas', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-016', 'Furadeira de impacto', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-017', 'Serra copo 63/70 mm (furo de parede)', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-018', 'Extensão elétrica 20 m', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-019', 'Escada de alumínio 7 degraus', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-020', 'Nível de bolha 40 cm', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-021', 'Trena 5 m', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-022', 'Alicate universal / corte / bico (jogo)', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-023', 'Chave de fenda e Phillips (jogo)', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-024', 'Lanterna de cabeça', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('FER-025', 'Maleta/bolsa de ferramentas do técnico', 'peca', 'ferramenta', 'FERRAMENTAS', 'un', 1, 'un', 0, null, null),
  ('APA-001', 'Condicionador de ar split hi-wall inverter 9.000 BTU/h, R-32, 220 V, Selo Procel A', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-002', 'Condicionador de ar split hi-wall inverter 12.000 BTU/h, R-32, 220 V, Selo Procel A', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-003', 'Condicionador de ar split hi-wall inverter 18.000 BTU/h, R-32, 220 V, Selo Procel A', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-004', 'Condicionador de ar split hi-wall inverter 24.000 BTU/h, R-32, 220 V, Selo Procel A', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-005', 'Condicionador de ar split hi-wall inverter 30.000 BTU/h, R-32, 220 V, Selo Procel A', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-006', 'Condicionador de ar split piso-teto 36.000 BTU/h, R-410A/R-32, 220/380 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-007', 'Condicionador de ar split piso-teto 48.000 BTU/h, R-410A/R-32, 220/380 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-008', 'Condicionador de ar split piso-teto 60.000 BTU/h, R-410A/R-32, 220/380 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-009', 'Condicionador de ar split piso-teto 80.000 BTU/h, R-410A/R-32, 220/380 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-010', 'Condicionador de ar split cassete 4 vias 36.000 BTU/h, 220/380 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-011', 'Condicionador de ar split cassete 4 vias 48.000 BTU/h, 220/380 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-012', 'Condicionador de ar split cassete 4 vias 60.000 BTU/h, 220/380 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-013', 'Condicionador de ar de janela 10.000 BTU/h, 220 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-014', 'Condicionador de ar de janela 12.000 BTU/h, 220 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-015', 'Condicionador de ar de janela 18.000 BTU/h, 220 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-016', 'Desumidificador de ar portátil (paiol/depósito), 220 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null),
  ('APA-017', 'Cortina de ar 90/120 cm, 220 V', 'peca', 'aparelho', 'APARELHOS', 'un', 1, 'un', 0, null, null)
on conflict (codigo) do nothing;

insert into kits (id, nome, descricao, ordem) values
  ('inst-9-12k', 'Instalação split 9k–12k (até 3 m de linha)', 'Linha 1/4" + 3/8", 3 m. Somar metros extras de tubo e isolamento se a distância for maior.', 1),
  ('inst-18k', 'Instalação split 18k (até 3 m de linha)', 'Linha 1/4" + 1/2", 3 m. Somar metros extras de tubo e isolamento se a distância for maior.', 2),
  ('inst-24k', 'Instalação split 24k (até 3 m de linha)', 'Linha 1/4" + 5/8", 3 m. Somar metros extras de tubo e isolamento se a distância for maior.', 3),
  ('inst-36-48k', 'Instalação piso-teto 36k–48k (até 5 m de linha)', 'Linha 3/8" + 3/4", 5 m. Somar metros extras de tubo e isolamento se a distância for maior.', 4),
  ('inst-60k', 'Instalação piso-teto 60k (até 5 m de linha)', 'Linha 3/8" + 7/8", 5 m. Somar metros extras de tubo e isolamento se a distância for maior.', 5),
  ('prev-split', 'Preventiva mensal — split (por aparelho)', 'Limpeza de filtros, bandeja e verificação. Consumo médio por aparelho.', 6),
  ('limp-quimica', 'Limpeza química completa — split (por aparelho)', 'Evaporadora e condensadora, com bolsa coletora (ferramenta, não consome).', 7),
  ('vaz-r410', 'Reparo de vazamento + recarga R-410A (split até 24k)', 'Solda, teste com nitrogênio, vácuo e carga. Ajustar a massa de fluido pela placa do aparelho.', 8),
  ('vaz-r32', 'Reparo de vazamento + recarga R-32 (split até 24k)', 'Mesmo roteiro do R-410A com fluido R-32 (A2L — ferramentas compatíveis).', 9),
  ('troca-comp-12k', 'Troca de compressor 12k R-410A', 'Compressor, capacitor, filtro secador, solda prata, flushing, óleo, nitrogênio e carga.', 10),
  ('troca-cap', 'Troca de capacitores (compressor + ventilador)', 'Conferir µF e tensão na placa do aparelho; o kit usa os valores mais comuns em 12k.', 11),
  ('placa-univ', 'Troca por placa universal (split)', 'Placa, sensores e fixação.', 12),
  ('dreno', 'Desobstrução / refazer dreno', 'Troca de mangueira e conexões de dreno.', 13),
  ('bolsa-tecnico', 'Ferramental básico do técnico', 'Ferramentas e instrumentos (não consumíveis) para uma equipe de instalação.', 14)
on conflict (id) do nothing;

insert into kit_itens (kit_id, material_id, quantidade)
select v.kit_id, m.id, v.qtd from (values
  ('inst-9-12k', 'TUB-001', 3),
  ('inst-9-12k', 'TUB-002', 3),
  ('inst-9-12k', 'ISO-001', 3),
  ('inst-9-12k', 'ISO-002', 3),
  ('inst-9-12k', 'FLA-001', 2),
  ('inst-9-12k', 'FLA-002', 2),
  ('inst-9-12k', 'CON-008', 2),
  ('inst-9-12k', 'ISO-007', 1),
  ('inst-9-12k', 'ELE-003', 5),
  ('inst-9-12k', 'DRE-001', 4),
  ('inst-9-12k', 'FIX-001', 1),
  ('inst-9-12k', 'FIX-009', 4),
  ('inst-9-12k', 'FIX-008', 1),
  ('inst-9-12k', 'ELE-014', 1),
  ('inst-9-12k', 'ISO-018', 0.1),
  ('inst-9-12k', 'ISO-012', 0.5),
  ('inst-18k', 'TUB-001', 3),
  ('inst-18k', 'TUB-003', 3),
  ('inst-18k', 'ISO-001', 3),
  ('inst-18k', 'ISO-003', 3),
  ('inst-18k', 'FLA-001', 2),
  ('inst-18k', 'FLA-003', 2),
  ('inst-18k', 'CON-009', 2),
  ('inst-18k', 'ISO-007', 1),
  ('inst-18k', 'ELE-003', 5),
  ('inst-18k', 'DRE-001', 4),
  ('inst-18k', 'FIX-002', 1),
  ('inst-18k', 'FIX-009', 4),
  ('inst-18k', 'FIX-008', 1),
  ('inst-18k', 'ELE-015', 1),
  ('inst-18k', 'ISO-018', 0.1),
  ('inst-18k', 'ISO-012', 0.5),
  ('inst-24k', 'TUB-001', 3),
  ('inst-24k', 'TUB-004', 3),
  ('inst-24k', 'ISO-001', 3),
  ('inst-24k', 'ISO-004', 3),
  ('inst-24k', 'FLA-001', 2),
  ('inst-24k', 'FLA-004', 2),
  ('inst-24k', 'CON-010', 2),
  ('inst-24k', 'ISO-007', 1),
  ('inst-24k', 'ELE-004', 5),
  ('inst-24k', 'DRE-001', 4),
  ('inst-24k', 'FIX-003', 1),
  ('inst-24k', 'FIX-009', 4),
  ('inst-24k', 'FIX-008', 1),
  ('inst-24k', 'ELE-016', 1),
  ('inst-24k', 'ISO-018', 0.1),
  ('inst-24k', 'ISO-012', 0.5),
  ('inst-36-48k', 'TUB-002', 5),
  ('inst-36-48k', 'TUB-005', 5),
  ('inst-36-48k', 'ISO-002', 5),
  ('inst-36-48k', 'ISO-005', 5),
  ('inst-36-48k', 'FLA-002', 2),
  ('inst-36-48k', 'FLA-005', 2),
  ('inst-36-48k', 'CON-011', 2),
  ('inst-36-48k', 'ISO-007', 1),
  ('inst-36-48k', 'ELE-004', 7),
  ('inst-36-48k', 'DRE-001', 6),
  ('inst-36-48k', 'FIX-005', 1),
  ('inst-36-48k', 'FIX-009', 4),
  ('inst-36-48k', 'FIX-008', 1),
  ('inst-36-48k', 'ELE-017', 1),
  ('inst-36-48k', 'ISO-018', 0.1),
  ('inst-36-48k', 'ISO-012', 0.5),
  ('inst-60k', 'TUB-002', 5),
  ('inst-60k', 'TUB-006', 5),
  ('inst-60k', 'ISO-002', 5),
  ('inst-60k', 'ISO-006', 5),
  ('inst-60k', 'FLA-002', 2),
  ('inst-60k', 'CON-006', 2),
  ('inst-60k', 'CON-012', 2),
  ('inst-60k', 'ISO-007', 1),
  ('inst-60k', 'ELE-005', 7),
  ('inst-60k', 'DRE-001', 6),
  ('inst-60k', 'FIX-007', 1),
  ('inst-60k', 'FIX-009', 4),
  ('inst-60k', 'FIX-008', 1),
  ('inst-60k', 'ELE-021', 1),
  ('inst-60k', 'ISO-018', 0.1),
  ('inst-60k', 'ISO-012', 0.5),
  ('prev-split', 'QUI-003', 0.05),
  ('prev-split', 'QUI-004', 1),
  ('prev-split', 'QUI-009', 0.1),
  ('limp-quimica', 'QUI-002', 0.5),
  ('limp-quimica', 'QUI-001', 0.5),
  ('limp-quimica', 'QUI-003', 0.1),
  ('limp-quimica', 'QUI-004', 1),
  ('limp-quimica', 'QUI-009', 0.2),
  ('vaz-r410', 'SOL-001', 0.05),
  ('vaz-r410', 'SOL-005', 0.25),
  ('vaz-r410', 'GAS-007', 0.5),
  ('vaz-r410', 'CIC-001', 1),
  ('vaz-r410', 'FLA-001', 2),
  ('vaz-r410', 'FLA-002', 2),
  ('vaz-r410', 'GAS-001', 1.2),
  ('vaz-r410', 'QUI-007', 0.25),
  ('vaz-r32', 'SOL-001', 0.05),
  ('vaz-r32', 'SOL-005', 0.25),
  ('vaz-r32', 'GAS-007', 0.5),
  ('vaz-r32', 'CIC-001', 1),
  ('vaz-r32', 'FLA-001', 2),
  ('vaz-r32', 'FLA-002', 2),
  ('vaz-r32', 'GAS-002', 1),
  ('vaz-r32', 'QUI-007', 0.25),
  ('troca-comp-12k', 'CMP-002', 1),
  ('troca-comp-12k', 'CAP-013', 1),
  ('troca-comp-12k', 'CIC-001', 1),
  ('troca-comp-12k', 'SOL-002', 0.1),
  ('troca-comp-12k', 'SOL-001', 0.05),
  ('troca-comp-12k', 'SOL-005', 0.5),
  ('troca-comp-12k', 'QUI-006', 0.5),
  ('troca-comp-12k', 'GAS-008', 0.3),
  ('troca-comp-12k', 'GAS-007', 1),
  ('troca-comp-12k', 'GAS-001', 1.2),
  ('troca-cap', 'CAP-013', 1),
  ('troca-cap', 'CAP-002', 1),
  ('troca-cap', 'ELE-031', 0.02),
  ('troca-cap', 'ISO-010', 0.1),
  ('placa-univ', 'PLA-001', 1),
  ('placa-univ', 'PLA-004', 2),
  ('placa-univ', 'ELE-032', 0.1),
  ('placa-univ', 'ISO-018', 0.05),
  ('placa-univ', 'ISO-010', 0.1),
  ('dreno', 'DRE-001', 3),
  ('dreno', 'DRE-007', 2),
  ('dreno', 'DRE-005', 3),
  ('dreno', 'DRE-010', 0.1),
  ('dreno', 'QUI-005', 0.2),
  ('dreno', 'ISO-018', 0.05),
  ('bolsa-tecnico', 'INS-001', 1),
  ('bolsa-tecnico', 'INS-003', 1),
  ('bolsa-tecnico', 'INS-004', 1),
  ('bolsa-tecnico', 'INS-005', 1),
  ('bolsa-tecnico', 'INS-006', 1),
  ('bolsa-tecnico', 'INS-010', 1),
  ('bolsa-tecnico', 'FER-001', 1),
  ('bolsa-tecnico', 'FER-002', 1),
  ('bolsa-tecnico', 'FER-007', 1),
  ('bolsa-tecnico', 'FER-008', 1),
  ('bolsa-tecnico', 'FER-009', 1),
  ('bolsa-tecnico', 'FER-025', 1)
) as v(kit_id, codigo, qtd)
join materiais m on m.codigo = v.codigo
on conflict (kit_id, material_id) do nothing;

-- Conferência pós-aplicação:
-- select count(*) from materiais where codigo ~ '^[A-Z]{3}-[0-9]{3}$';   -- esperado: 318
-- select count(*) from kits;                                               -- esperado: 14
-- select count(*) from kit_itens;                                          -- esperado: 141
