-- ═══════════════════════════════════════════════════════════════════
-- 62 — CMASM Bio: seed das fichas de campo
-- ═══════════════════════════════════════════════════════════════════
-- O que é semeado e o que NÃO é, pela regra de D-eq-06: entra o que é
-- conhecimento público de espécie (nome, grupo, risco, orientação
-- genérica); NÃO entra árvore, presença nem serviço — são dados do
-- terreno da OM, registrados em campo, nunca inventados para a tela não
-- ficar vazia. `foto_url` fica nula: foto entra pela tela.
--
-- Idempotente pelo nome comum: rodar duas vezes não duplica.
-- Textos de "o que fazer" são orientação de conduta do observador, não
-- procedimento técnico — o procedimento é o serviço, registrado com
-- executor e materiais.
-- ═══════════════════════════════════════════════════════════════════

insert into bio_fichas
  (nome_comum, nome_cientifico, categoria, grupo, risco, peconhenta, descricao, o_que_fazer, controle)
select * from (values
  -- ── animais ──
  ('Capivara', 'Hydrochoerus hydrochaeris', 'animal', 'mamifero', 'baixo', false,
   'Maior roedor do mundo; vive em grupo perto de água. Hospedeiro do carrapato-estrela.',
   'Não alimentar nem se aproximar dos filhotes. Evitar a vegetação rasteira onde os grupos descansam (carrapatos).',
   'Sem controle direto. Roçada das áreas de descanso reduz o carrapato; ver ficha do carrapato-estrela.'),
  ('Jacaré-de-papo-amarelo', 'Caiman latirostris', 'animal', 'reptil', 'alto', false,
   'Jacaré de médio porte, comum em lagoas e canais do litoral fluminense.',
   'Manter distância. Não entrar na água. Avisar a DME e isolar o acesso à margem.',
   'Só resgate por equipe habilitada (Corpo de Bombeiros / órgão ambiental). Nunca capturar.'),
  ('Gambá', 'Didelphis aurita', 'animal', 'mamifero', 'baixo', false,
   'Marsupial noturno; entra em forros e depósitos atrás de comida.',
   'Não encurralar. Fecha-se o acesso depois que ele sai à noite.',
   'Vedar frestas de forro e depósito; lixo fechado. Captura só se ficar preso.'),
  ('Garça-branca', 'Ardea alba', 'animal', 'ave', 'baixo', false,
   'Ave pernalta de margens de água; indicador de lagoa saudável.',
   'Nenhuma ação. Não perturbar ninhos.',
   'Não se aplica.'),
  ('Urubu', 'Coragyps atratus', 'animal', 'ave', 'baixo', false,
   'Ave de rapina necrófaga; concentra-se onde há resíduo orgânico exposto.',
   'Não alimentar. Presença em bando indica resíduo mal acondicionado.',
   'Acondicionamento do lixo orgânico; retirada de carcaças.'),
  ('Bem-te-vi', 'Pitangus sulphuratus', 'animal', 'ave', 'baixo', false,
   'Ave comum e territorial; ninho em árvores e estruturas.',
   'Nenhuma ação.',
   'Não se aplica.'),
  ('Tilápia', 'Oreochromis niloticus', 'animal', 'peixe', 'baixo', false,
   'Peixe exótico de água doce, muito comum em lagoas e reservatórios.',
   'Nenhuma ação.',
   'Controle populacional só com orientação do órgão ambiental.'),
  ('Jararaca', 'Bothrops jararaca', 'animal', 'reptil', 'alto', true,
   'Serpente peçonhenta mais comum do Sudeste. Marrom com desenhos em V invertido; ativa ao entardecer.',
   'Afastar-se devagar. Não tentar matar nem capturar. Isolar a área e avisar a DME. Em caso de picada: imobilizar, não fazer torniquete, levar ao hospital com soro.',
   'Roçada e retirada de entulho (abrigo de roedores, que são o alimento). Captura por equipe habilitada.'),
  ('Cobra-cipó', 'Chironius spp.', 'animal', 'reptil', 'baixo', false,
   'Serpente arborícola fina e ágil, verde ou marrom. Não peçonhenta; morde se manuseada.',
   'Deixar seguir. Não manusear.',
   'Não se aplica.'),
  ('Cobra-coral-verdadeira', 'Micrurus corallinus', 'animal', 'reptil', 'alto', true,
   'Anéis vermelhos, pretos e brancos. Peçonhenta; peçonha neurotóxica. Dócil, mas morde se pisada ou manuseada.',
   'Não tocar em hipótese alguma. Isolar e avisar a DME. Picada: hospital imediato.',
   'Captura por equipe habilitada.'),
  ('Teiú', 'Salvator merianae', 'animal', 'reptil', 'medio', false,
   'Lagarto grande (até 1,5 m). Mordida forte e chicotada de cauda quando acuado. Come ovos e restos.',
   'Não encurralar. Manter distância; ele foge se tiver saída.',
   'Vedar acesso a depósitos de alimento e lixo.'),
  ('Morcego', 'Chiroptera (diversos)', 'animal', 'mamifero', 'medio', false,
   'Colônias em forros, casas de máquinas e estruturas fechadas. Guano e risco de raiva em animal caído.',
   'Não tocar em morcego caído ou com comportamento estranho (raiva). Avisar a DME.',
   'Vedar acesso após saída noturna; nunca aplicar veneno (é fauna protegida). Limpeza do guano com EPI.'),
  -- ── pragas ──
  ('Carrapato-estrela', 'Amblyomma sculptum', 'praga', 'aracnideo', 'alto', false,
   'Vetor da febre maculosa. Associado às áreas de descanso de capivaras e a vegetação rasteira.',
   'Após passar por área de risco, inspecionar corpo e roupa. Retirar carrapato com pinça, sem esmagar. Febre e manchas dias depois: procurar médico e citar a exposição.',
   'Roçada e manutenção das áreas de descanso das capivaras; acaricida só por empresa habilitada.'),
  ('Cupim', 'Isoptera (diversos)', 'praga', 'inseto', 'medio', false,
   'Cupim de madeira seca (túneis dentro da peça) e cupim subterrâneo (túneis de terra nas paredes).',
   'Não mexer no ninho. Marcar a peça e avisar a DME.',
   'Descupinização por empresa habilitada; substituição de madeira comprometida.'),
  ('Formiga-cortadeira', 'Atta sexdens / Acromyrmex', 'praga', 'inseto', 'medio', false,
   'Saúva e quenquém. Cortam folhas de árvores e gramado; olheiros e panelas visíveis no solo.',
   'Nenhuma ação individual. Registrar o formigueiro no mapa.',
   'Isca granulada no olheiro ativo em dia seco; termonebulização em formigueiro grande. Empresa habilitada.'),
  ('Rato', 'Rattus rattus / Rattus norvegicus', 'praga', 'roedor', 'alto', false,
   'Rato-de-telhado (forro, árvores) e ratazana (esgoto, solo). Vetor de leptospirose e atrai serpentes.',
   'Não tocar em fezes e urina sem luva. Registrar trilhas e fezes.',
   'Desratização por empresa habilitada (isca em porta-isca); vedação e lixo fechado.'),
  ('Vespa / marimbondo', 'Vespidae (diversos)', 'praga', 'inseto', 'alto', true,
   'Ninho de papel em beirais, árvores e caixas elétricas. Ataca em grupo quando o ninho é perturbado.',
   'Afastar-se sem movimentos bruscos. Nunca bater no ninho. Alérgico picado: hospital.',
   'Remoção do ninho à noite por equipe com EPI; inseticida só por empresa habilitada.'),
  ('Abelha (colmeia)', 'Apis mellifera', 'praga', 'inseto', 'alto', true,
   'Enxame ou colmeia estabelecida em oco de árvore, forro ou caixa. Africanizada: defensiva.',
   'Isolar 50 m. Não usar inseticida nem fumaça. Avisar a DME.',
   'Remoção por apicultor (a colmeia é reaproveitada, não morta). Bombeiros só em risco imediato.'),
  ('Caramujo-africano', 'Lissachatina fulica', 'praga', 'molusco', 'medio', false,
   'Caramujo grande, concha listrada. Hospedeiro de parasitas; nunca manusear sem luva.',
   'Não tocar sem luva. Não esmagar com o pé.',
   'Coleta manual com luva, imersão em salmoura, descarte fechado. Sem veneno (afeta fauna).'),
  ('Mosquito Aedes', 'Aedes aegypti', 'praga', 'inseto', 'alto', false,
   'Vetor de dengue, zika e chikungunya. Cria em água parada limpa: ralos, calhas, pneus, bandejas de ar-condicionado.',
   'Eliminar o foco visto. Registrar o ponto.',
   'Vistoria semanal de criadouros; larvicida em ralo e caixa d''água por equipe treinada.'),
  ('Barata', 'Periplaneta americana / Blattella germanica', 'praga', 'inseto', 'medio', false,
   'Barata americana (esgoto, caixas de passagem) e alemã (cozinha, rancho).',
   'Registrar onde aparece em quantidade.',
   'Desinsetização por empresa habilitada; gel em fresta; vedação de ralos.'),
  ('Pombo', 'Columba livia', 'praga', 'ave', 'medio', false,
   'Pomba doméstica em beirais e forros. Fezes corroem estrutura e carregam fungos (criptococose).',
   'Não alimentar. Limpeza de fezes só com EPI e umedecendo antes.',
   'Barreira física (rede, espícula); nunca veneno. Retirada de ninho por equipe.'),
  -- ── árvores ──
  ('Mangueira', 'Mangifera indica', 'arvore', 'arvore', 'baixo', false,
   'Copa larga e densa; frutos no verão. Galhos pesados quebram em vendaval.',
   'Manter distância em ventania. Fruto no chão atrai fauna.',
   'Poda de limpeza anual antes do verão; poda de galho seco ou rachado.'),
  ('Amendoeira-da-praia', 'Terminalia catappa', 'arvore', 'arvore', 'medio', false,
   'Galhos horizontais em andares; madeira quebradiça. Muito comum em orla.',
   'Não estacionar sob galhos grandes em ventania.',
   'Poda de redução e limpeza a cada 12 meses; avaliar galhos sobre passagem.'),
  ('Ficus', 'Ficus benjamina', 'arvore', 'arvore', 'medio', false,
   'Raízes agressivas levantam calçada e entram em rede de esgoto e fundação.',
   'Registrar calçada levantada perto do tronco.',
   'Poda de contenção; barreira de raiz; avaliar supressão perto de edificação.'),
  ('Jaqueira', 'Artocarpus heterophyllus', 'arvore', 'arvore', 'medio', false,
   'Frutos de até 30 kg presos ao tronco; queda causa acidente.',
   'Não permanecer sob a copa na época de fruto (verão).',
   'Retirada dos frutos antes de maduros; poda de limpeza.'),
  ('Palmeira-imperial', 'Roystonea oleracea', 'arvore', 'arvore', 'medio', false,
   'Folhas de até 5 m e 20 kg caem inteiras ao secar.',
   'Registrar folha seca pendente sobre passagem.',
   'Retirada de folhas secas e cachos a cada 6 meses.'),
  ('Ipê', 'Handroanthus spp.', 'arvore', 'arvore', 'baixo', false,
   'Floração amarela, rosa ou roxa no inverno; madeira resistente.',
   'Nenhuma ação.',
   'Poda de formação só nos primeiros anos; depois só limpeza.'),
  ('Flamboyant', 'Delonix regia', 'arvore', 'arvore', 'medio', false,
   'Copa larga, raízes superficiais; tomba em solo encharcado e vento forte.',
   'Registrar inclinação do tronco ou raiz exposta.',
   'Poda de redução de copa; avaliar estabilidade após temporal.')
) as v(nome_comum, nome_cientifico, categoria, grupo, risco, peconhenta, descricao, o_que_fazer, controle)
where not exists (select 1 from bio_fichas f where f.nome_comum = v.nome_comum);

-- verificação: select categoria, count(*) from bio_fichas group by 1;  → animal 12 · praga 10 · arvore 7
